"""Type stubs for `rapier._rapier2d` (2D, f32).

Phase 02: math layer only.
"""

from __future__ import annotations

from typing import Any, Iterator, Tuple, Union

import numpy as np

__version__: str

# ---- Exception tree -------------------------------------------------------
class RapierError(Exception): ...
class InvalidHandle(RapierError): ...
class MeshConversionError(RapierError): ...
class UrdfError(RapierError): ...
class MjcfError(RapierError): ...
class SerializationError(RapierError): ...
class QueryFailure(RapierError): ...
class MeshLoaderError(RapierError): ...

VectorLike = Union[
    "Vec2",
    "Point2",
    Tuple[float, float],
    list,
    "np.ndarray",
]
RotationLike = Union["Rotation2", float, Tuple[float], list, "np.ndarray"]
IsometryLike = Union["Isometry2", Tuple[VectorLike, RotationLike]]

# ---- Vec2 ----------------------------------------------------------------
class Vec2:
    def __init__(self, x: float, y: float) -> None: ...
    @staticmethod
    def zeros() -> Vec2: ...
    @staticmethod
    def unit_x() -> Vec2: ...
    @staticmethod
    def unit_y() -> Vec2: ...
    @staticmethod
    def from_tuple(t: VectorLike) -> Vec2: ...
    @staticmethod
    def from_ndarray(a: np.ndarray) -> Vec2: ...

    x: float
    y: float

    def dot(self, other: VectorLike) -> float: ...
    def norm(self) -> float: ...
    def norm_squared(self) -> float: ...
    def normalize(self) -> Vec2: ...
    def lerp(self, other: VectorLike, t: float) -> Vec2: ...
    def to_tuple(self) -> Tuple[float, float]: ...
    def to_ndarray(self) -> np.ndarray: ...
    def bitwise_equal(self, other: Vec2) -> bool: ...

    def __add__(self, other: VectorLike) -> Vec2: ...
    def __sub__(self, other: VectorLike) -> Vec2: ...
    def __mul__(self, scalar: float) -> Vec2: ...
    def __rmul__(self, scalar: float) -> Vec2: ...
    def __truediv__(self, scalar: float) -> Vec2: ...
    def __neg__(self) -> Vec2: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> float: ...
    def __iter__(self) -> Iterator[float]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

# ---- Point2 --------------------------------------------------------------
class Point2:
    def __init__(self, x: float, y: float) -> None: ...
    @staticmethod
    def origin() -> Point2: ...
    @staticmethod
    def from_tuple(t: VectorLike) -> Point2: ...
    @staticmethod
    def from_ndarray(a: np.ndarray) -> Point2: ...

    x: float
    y: float
    coords: Vec2

    def to_tuple(self) -> Tuple[float, float]: ...
    def to_ndarray(self) -> np.ndarray: ...
    def bitwise_equal(self, other: Point2) -> bool: ...

    def __add__(self, v: VectorLike) -> Point2: ...
    def __sub__(self, other: Any) -> Union[Point2, Vec2]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> float: ...
    def __iter__(self) -> Iterator[float]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

# ---- Rotation2 -----------------------------------------------------------
class Rotation2:
    def __init__(self, angle: float) -> None: ...
    @staticmethod
    def identity() -> Rotation2: ...
    @staticmethod
    def from_angle(angle: float) -> Rotation2: ...

    angle: float
    cos_angle: float
    sin_angle: float

    def inverse(self) -> Rotation2: ...
    def to_matrix(self) -> np.ndarray: ...
    def transform_point(self, p: VectorLike) -> Point2: ...
    def transform_vector(self, v: VectorLike) -> Vec2: ...
    def slerp(self, other: RotationLike, t: float) -> Rotation2: ...
    def bitwise_equal(self, other: Rotation2) -> bool: ...

    def __mul__(self, rhs: Any) -> Any: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

# ---- Isometry2 -----------------------------------------------------------
class Isometry2:
    def __init__(
        self,
        translation: VectorLike | None = None,
        rotation: RotationLike | None = None,
    ) -> None: ...
    @staticmethod
    def identity() -> Isometry2: ...
    @staticmethod
    def from_translation(x: float, y: float) -> Isometry2: ...
    @staticmethod
    def from_rotation(angle: float) -> Isometry2: ...

    @property
    def translation(self) -> Vec2: ...
    @property
    def rotation(self) -> Rotation2: ...

    def inverse(self) -> Isometry2: ...
    def transform_point(self, p: VectorLike) -> Point2: ...
    def transform_vector(self, v: VectorLike) -> Vec2: ...
    def to_matrix(self) -> np.ndarray: ...
    def lerp_slerp(self, other: Isometry2, t: float) -> Isometry2: ...
    def bitwise_equal(self, other: Isometry2) -> bool: ...

    def __mul__(self, rhs: Any) -> Any: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

# ---- Free helpers --------------------------------------------------------
def rotation_from_angle(angle: float) -> Rotation2: ...

# =====================================================================
# Phase 03 — Dynamics (2D)
# =====================================================================

import enum

class RigidBodyType(enum.IntEnum):
    DYNAMIC: int
    FIXED: int
    KINEMATIC_VELOCITY_BASED: int
    KINEMATIC_POSITION_BASED: int

class CoefficientCombineRule(enum.IntEnum):
    AVERAGE: int
    MIN: int
    MULTIPLY: int
    MAX: int
    CLAMPED_SUM: int

# Note: no FrictionModel in 2D.

class ColliderHandle:
    def __init__(self, index: int = 0, generation: int = 0) -> None: ...
    @staticmethod
    def from_raw_parts(index: int, generation: int) -> ColliderHandle: ...
    @staticmethod
    def invalid() -> ColliderHandle: ...
    @property
    def index(self) -> int: ...
    @property
    def generation(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class ColliderSet:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...

class ImpulseJointSet:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...

class MultibodyJointSet:
    def __init__(self) -> None: ...

class RigidBodyHandle:
    def __init__(self, index: int = 0, generation: int = 0) -> None: ...
    @staticmethod
    def from_raw_parts(index: int, generation: int) -> RigidBodyHandle: ...
    @staticmethod
    def invalid() -> RigidBodyHandle: ...
    @property
    def index(self) -> int: ...
    @property
    def generation(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class LockedAxes:
    TRANSLATION_LOCKED_X: LockedAxes
    TRANSLATION_LOCKED_Y: LockedAxes
    TRANSLATION_LOCKED: LockedAxes
    ROTATION_LOCKED: LockedAxes
    ALL: LockedAxes
    def __init__(self, bits: int = 0) -> None: ...
    @staticmethod
    def empty() -> LockedAxes: ...
    @staticmethod
    def all_axes() -> LockedAxes: ...
    @property
    def bits(self) -> int: ...

class RigidBodyActivation:
    sleep_threshold: float
    linear_threshold: float
    angular_threshold: float
    time_until_sleep: float
    sleeping: bool
    def __init__(self) -> None: ...
    @staticmethod
    def active() -> RigidBodyActivation: ...
    @staticmethod
    def inactive() -> RigidBodyActivation: ...
    @staticmethod
    def cannot_sleep() -> RigidBodyActivation: ...
    def is_active(self) -> bool: ...

class SpringCoefficients:
    stiffness: float
    damping: float
    def __init__(self, stiffness: float = 30.0, damping: float = 5.0) -> None: ...
    @staticmethod
    def contact_defaults() -> SpringCoefficients: ...
    @staticmethod
    def joint_defaults() -> SpringCoefficients: ...

class MassProperties:
    def __init__(self, local_com: VectorLike | None = None, mass: float = 0.0, principal_inertia: float = 0.0) -> None: ...
    @staticmethod
    def zero() -> MassProperties: ...
    @staticmethod
    def from_ball(density: float, radius: float) -> MassProperties: ...
    @staticmethod
    def from_cuboid(density: float, half_extents: VectorLike) -> MassProperties: ...
    @staticmethod
    def from_capsule(density: float, a: VectorLike, b: VectorLike, radius: float) -> MassProperties: ...
    @property
    def mass(self) -> float: ...
    @property
    def inv_mass(self) -> float: ...
    @property
    def local_com(self) -> Point2: ...
    @property
    def principal_inertia(self) -> float: ...

class RigidBodyAdditionalMassProps:
    @staticmethod
    def from_mass(mass: float) -> RigidBodyAdditionalMassProps: ...
    @staticmethod
    def from_mass_properties(mp: MassProperties) -> RigidBodyAdditionalMassProps: ...

class RigidBodyDamping:
    linear_damping: float
    angular_damping: float

class RigidBodyDominance:
    group: int

class RigidBodyCcd:
    ccd_enabled: bool
    soft_ccd_prediction: float

class RigidBodyVelocity:
    linvel: Vec2
    angvel: float

class RigidBodyForces:
    force: Vec2
    torque: float
    gravity_scale: float

class RigidBodyMassProps:
    local_mprops: MassProperties

class RigidBodyPosition:
    position: Isometry2
    next_position: Isometry2

class IntegrationParameters:
    dt: float
    min_ccd_dt: float
    warmstart_coefficient: float
    length_unit: float
    normalized_allowed_linear_error: float
    normalized_max_corrective_velocity: float
    normalized_prediction_distance: float
    num_solver_iterations: int
    num_internal_pgs_iterations: int
    num_internal_stabilization_iterations: int
    min_island_size: int
    max_ccd_substeps: int
    contact_softness: SpringCoefficients
    def __init__(self) -> None: ...
    @staticmethod
    def default_params() -> IntegrationParameters: ...

class IslandManager:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def active_dynamic_set(self) -> list[RigidBodyHandle]: ...

class CCDSolver:
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def solve_ccd(self, *args: Any, **kwargs: Any) -> None: ...

class RigidBodyBuilder:
    def __init__(self, body_type: RigidBodyType = ...) -> None: ...
    def translation(self, v: VectorLike) -> RigidBodyBuilder: ...
    def rotation(self, angle: float) -> RigidBodyBuilder: ...
    def position(self, p: IsometryLike) -> RigidBodyBuilder: ...
    def linvel(self, v: VectorLike) -> RigidBodyBuilder: ...
    def angvel(self, a: float) -> RigidBodyBuilder: ...
    def linear_damping(self, f: float) -> RigidBodyBuilder: ...
    def angular_damping(self, f: float) -> RigidBodyBuilder: ...
    def gravity_scale(self, f: float) -> RigidBodyBuilder: ...
    def can_sleep(self, b: bool) -> RigidBodyBuilder: ...
    def sleeping(self, b: bool) -> RigidBodyBuilder: ...
    def ccd_enabled(self, b: bool) -> RigidBodyBuilder: ...
    def soft_ccd_prediction(self, f: float) -> RigidBodyBuilder: ...
    def dominance_group(self, g: int) -> RigidBodyBuilder: ...
    def additional_mass(self, m: float) -> RigidBodyBuilder: ...
    def locked_axes(self, la: LockedAxes) -> RigidBodyBuilder: ...
    def build(self) -> RigidBody: ...

class RigidBody:
    position: Isometry2
    translation: Vec2
    rotation: Rotation2
    linvel: Vec2
    angvel: float
    user_data: int
    body_type: RigidBodyType
    locked_axes: LockedAxes
    @staticmethod
    def dynamic(**kwargs: Any) -> RigidBodyBuilder: ...
    @staticmethod
    def fixed(**kwargs: Any) -> RigidBodyBuilder: ...
    @staticmethod
    def kinematic_velocity_based(**kwargs: Any) -> RigidBodyBuilder: ...
    @staticmethod
    def kinematic_position_based(**kwargs: Any) -> RigidBodyBuilder: ...
    @staticmethod
    def new_body(body_type: RigidBodyType, **kwargs: Any) -> RigidBodyBuilder: ...
    def add_force(self, force: VectorLike, wake_up: bool = True) -> None: ...
    def add_torque(self, torque: float, wake_up: bool = True) -> None: ...
    def apply_impulse(self, impulse: VectorLike, wake_up: bool = True) -> None: ...
    def apply_torque_impulse(self, torque_impulse: float, wake_up: bool = True) -> None: ...
    def reset_forces(self, wake_up: bool = True) -> None: ...
    def wake_up(self, strong: bool = True) -> None: ...
    def sleep(self) -> None: ...
    def kinetic_energy(self) -> float: ...
    def recompute_mass_properties_from_colliders(self, colliders: ColliderSet) -> None: ...
    def set_additional_mass(self, mass: float, wake_up: bool = True) -> None: ...

class RigidBodySet:
    def __init__(self) -> None: ...
    def insert(self, body: RigidBody | RigidBodyBuilder) -> RigidBodyHandle: ...
    def remove(self, handle: RigidBodyHandle, islands: IslandManager, colliders: ColliderSet, impulse_joints: ImpulseJointSet, multibody_joints: MultibodyJointSet, remove_attached_colliders: bool = True) -> RigidBody | None: ...
    def get(self, handle: RigidBodyHandle) -> RigidBody | None: ...
    def replace(self, handle: RigidBodyHandle, body: RigidBody) -> None: ...
    def __getitem__(self, handle: RigidBodyHandle) -> RigidBody: ...
    def __contains__(self, handle: RigidBodyHandle) -> bool: ...
    def __len__(self) -> int: ...

# ---- events / hooks (phase 07) -------------------------------------------

class SolverFlags:
    COMPUTE_IMPULSES: SolverFlags
    EMPTY: SolverFlags
    def __init__(self, bits: int = 0) -> None: ...
    @staticmethod
    def empty() -> SolverFlags: ...
    @property
    def bits(self) -> int: ...
    def contains(self, other: SolverFlags) -> bool: ...
    def is_empty(self) -> bool: ...
    def __or__(self, other: SolverFlags) -> SolverFlags: ...
    def __and__(self, other: SolverFlags) -> SolverFlags: ...
    def __xor__(self, other: SolverFlags) -> SolverFlags: ...
    def __invert__(self) -> SolverFlags: ...

class PairFilterContext:
    @property
    def collider1(self) -> ColliderHandle: ...
    @property
    def collider2(self) -> ColliderHandle: ...
    @property
    def rigid_body1(self) -> RigidBodyHandle | None: ...
    @property
    def rigid_body2(self) -> RigidBodyHandle | None: ...

class ContactModificationContext:
    @property
    def collider1(self) -> ColliderHandle: ...
    @property
    def collider2(self) -> ColliderHandle: ...
    @property
    def rigid_body1(self) -> RigidBodyHandle | None: ...
    @property
    def rigid_body2(self) -> RigidBodyHandle | None: ...
    @property
    def local_n1(self) -> Vec2: ...
    @property
    def local_n2(self) -> Vec2: ...
    normal: Vec2
    user_data: int
    @property
    def solver_contacts(self) -> list[SolverContact]: ...
    def clear_solver_contacts(self) -> None: ...
    def num_solver_contacts(self) -> int: ...
    def remove_solver_contact(self, i: int) -> None: ...
    def update_as_oneway_platform(self, allowed_local_n1: Vec2 | tuple[float, float], angle: float) -> None: ...

class ChannelEventCollector:
    def __init__(self) -> None: ...
    def drain_collision_events(self) -> list[CollisionEvent]: ...
    def drain_contact_force_events(self) -> list[ContactForceEvent]: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...

# ---- controllers (phase 08) ----------------------------------------------
# 2D variant: no DynamicRayCastVehicleController / Wheel / RayCastInfo (3D-only upstream).

from typing import Callable, Literal

class CharacterLength:
    kind: Literal["absolute", "relative"]
    value: float
    def __init__(self, value: float = 0.0, kind: str = "absolute") -> None: ...
    @staticmethod
    def absolute(value: float) -> CharacterLength: ...
    @staticmethod
    def relative(value: float) -> CharacterLength: ...

class CharacterAutostep:
    max_height: CharacterLength
    min_width: CharacterLength
    include_dynamic_bodies: bool
    def __init__(
        self,
        max_height: CharacterLength | float | None = None,
        min_width: CharacterLength | float | None = None,
        include_dynamic_bodies: bool = True,
    ) -> None: ...
    @staticmethod
    def disabled() -> None: ...

class EffectiveCharacterMovement:
    @property
    def translation(self) -> Vec2: ...
    @property
    def grounded(self) -> bool: ...
    @property
    def is_sliding_down_slope(self) -> bool: ...

class CharacterCollision:
    @property
    def handle(self) -> ColliderHandle: ...
    @property
    def character_pos(self) -> Isometry2: ...
    @property
    def translation_applied(self) -> Vec2: ...
    @property
    def translation_remaining(self) -> Vec2: ...
    @property
    def toi(self) -> ShapeCastHit: ...

class KinematicCharacterController:
    up: Vec2
    offset: CharacterLength
    slide: bool
    autostep: CharacterAutostep | None
    max_slope_climb_angle: float
    min_slope_slide_angle: float
    snap_to_ground: CharacterLength | None
    normal_nudge_factor: float
    def __init__(
        self,
        *,
        up: Vec2 | tuple[float, float] | None = None,
        offset: CharacterLength | float | None = None,
        slide: bool | None = None,
        autostep: CharacterAutostep | None = None,
        max_slope_climb_angle: float | None = None,
        min_slope_slide_angle: float | None = None,
        snap_to_ground: CharacterLength | float | None = None,
        normal_nudge_factor: float | None = None,
    ) -> None: ...
    def move_shape(
        self,
        dt: float,
        bodies: RigidBodySet,
        colliders: ColliderSet,
        queries: QueryPipeline,
        shape: SharedShape,
        shape_pos: Isometry2,
        desired_translation: Vec2 | tuple[float, float],
        filter: QueryFilter | None = None,
        events_callback: Callable[[CharacterCollision], None] | None = None,
    ) -> EffectiveCharacterMovement: ...
    def solve_character_collision_impulses(
        self,
        dt: float,
        bodies: RigidBodySet,
        colliders: ColliderSet,
        queries: QueryPipeline,
        character_shape: SharedShape,
        character_pos: Isometry2,
        character_mass: float,
        collisions: list[CharacterCollision],
        filter: QueryFilter | None = None,
    ) -> None: ...

class AxesMask:
    LIN_X: AxesMask
    LIN_Y: AxesMask
    ANG_Z: AxesMask
    def __init__(self, bits: int = 0) -> None: ...
    @staticmethod
    def empty() -> AxesMask: ...
    @staticmethod
    def all() -> AxesMask: ...
    @staticmethod
    def all_axes() -> AxesMask: ...
    @property
    def bits(self) -> int: ...
    def contains(self, other: AxesMask) -> bool: ...
    def is_empty(self) -> bool: ...
    def __or__(self, other: AxesMask) -> AxesMask: ...
    def __and__(self, other: AxesMask) -> AxesMask: ...
    def __xor__(self, other: AxesMask) -> AxesMask: ...
    def __invert__(self) -> AxesMask: ...
    def __sub__(self, other: AxesMask) -> AxesMask: ...
    def __contains__(self, other: AxesMask) -> bool: ...

class PdErrors:
    linear: Vec2
    angular: float
    def __init__(
        self,
        linear: Vec2 | tuple[float, float] | None = None,
        angular: float | None = None,
    ) -> None: ...

class PidCorrection:
    @property
    def linear(self) -> Vec2: ...
    @property
    def angular(self) -> float: ...

class PdController:
    axes: AxesMask
    def __init__(
        self,
        axes: AxesMask | None = None,
        Kp: Vec2 | tuple[float, float] | float | None = None,
        Kd: Vec2 | tuple[float, float] | float | None = None,
    ) -> None: ...
    def set_axes_kp(self, v: Vec2 | tuple[float, float]) -> None: ...
    def set_axes_kd(self, v: Vec2 | tuple[float, float]) -> None: ...
    def rigid_body_correction(self, body: RigidBody, target_pose: Isometry2) -> PidCorrection: ...
    def correction(self, pose_errors: PdErrors, vel_errors: PdErrors) -> PidCorrection: ...

class PidController:
    axes: AxesMask
    def __init__(
        self,
        axes: AxesMask | None = None,
        Kp: Vec2 | tuple[float, float] | float | None = None,
        Ki: Vec2 | tuple[float, float] | float | None = None,
        Kd: Vec2 | tuple[float, float] | float | None = None,
    ) -> None: ...
    def set_axes_kp(self, v: Vec2 | tuple[float, float]) -> None: ...
    def set_axes_ki(self, v: Vec2 | tuple[float, float]) -> None: ...
    def set_axes_kd(self, v: Vec2 | tuple[float, float]) -> None: ...
    def reset(self) -> None: ...
    def rigid_body_correction(self, dt: float, body: RigidBody, target_pose: Isometry2) -> PidCorrection: ...
    def position_correction(self, dt: float, position: Isometry2, target_position: Isometry2) -> PidCorrection: ...
    def update(self, dt: float, pose_errors: PdErrors, vel_errors: PdErrors) -> PidCorrection: ...

# ---- debug-render (phase 10) ---------------------------------------------

class DebugRenderObject:
    kind: int
    RIGID_BODY: DebugRenderObject
    COLLIDER: DebugRenderObject
    COLLIDER_AABB: DebugRenderObject
    IMPULSE_JOINT: DebugRenderObject
    MULTIBODY_JOINT: DebugRenderObject
    CONTACT_PAIR: DebugRenderObject

class DebugColor:
    def __init__(self, h: float = 0.0, s: float = 0.0, l: float = 0.0, a: float = 1.0) -> None: ...
    @staticmethod
    def from_hsla(h: float, s: float, l: float, a: float) -> DebugColor: ...
    @staticmethod
    def from_rgba(r: float, g: float, b: float, a: float) -> DebugColor: ...
    @property
    def hsla(self) -> list[float]: ...
    @property
    def rgba(self) -> list[float]: ...

class DebugRenderMode:
    def __init__(self, bits: int = 0) -> None: ...
    @staticmethod
    def empty() -> DebugRenderMode: ...
    @staticmethod
    def default() -> DebugRenderMode: ...
    @staticmethod
    def all() -> DebugRenderMode: ...
    COLLIDER_SHAPES: DebugRenderMode
    RIGID_BODY_AXES: DebugRenderMode
    MULTIBODY_JOINTS: DebugRenderMode
    IMPULSE_JOINTS: DebugRenderMode
    JOINTS: DebugRenderMode
    SOLVER_CONTACTS: DebugRenderMode
    CONTACTS: DebugRenderMode
    COLLIDER_AABBS: DebugRenderMode
    EMPTY: DebugRenderMode
    @property
    def bits(self) -> int: ...
    def contains(self, other: DebugRenderMode) -> bool: ...
    def is_empty(self) -> bool: ...
    def __or__(self, other: DebugRenderMode) -> DebugRenderMode: ...
    def __and__(self, other: DebugRenderMode) -> DebugRenderMode: ...
    def __xor__(self, other: DebugRenderMode) -> DebugRenderMode: ...
    def __invert__(self) -> DebugRenderMode: ...
    def __bool__(self) -> bool: ...

class DebugRenderStyle:
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> DebugRenderStyle: ...
    subdivisions: int
    border_subdivisions: int
    collider_dynamic_color: DebugColor
    collider_fixed_color: DebugColor
    collider_kinematic_color: DebugColor
    collider_parentless_color: DebugColor
    impulse_joint_anchor_color: DebugColor
    impulse_joint_separation_color: DebugColor
    multibody_joint_anchor_color: DebugColor
    multibody_joint_separation_color: DebugColor
    sleep_color_multiplier: DebugColor
    disabled_color_multiplier: DebugColor
    rigid_body_axes_length: float
    contact_depth_color: DebugColor
    contact_normal_color: DebugColor
    contact_normal_length: float
    collider_aabb_color: DebugColor

class DebugLineCollector:
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def lines(self) -> np.ndarray: ...
    def colors(self) -> np.ndarray: ...
    def objects(self) -> np.ndarray: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[tuple[DebugRenderObject, Vec2, Vec2, DebugColor]]: ...

class DebugRenderPipeline:
    mode: DebugRenderMode
    style: DebugRenderStyle
    def __init__(
        self,
        mode: DebugRenderMode | None = None,
        style: DebugRenderStyle | None = None,
    ) -> None: ...
    def render(
        self,
        bodies: RigidBodySet,
        colliders: ColliderSet,
        impulse_joints: ImpulseJointSet,
        multibody_joints: MultibodyJointSet,
        narrow_phase: NarrowPhase,
        backend: Any,
    ) -> None: ...
    def render_to_arrays(
        self,
        bodies: RigidBodySet,
        colliders: ColliderSet,
        impulse_joints: ImpulseJointSet,
        multibody_joints: MultibodyJointSet,
        narrow_phase: NarrowPhase,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...
