[package]
name = "rapier3d-f64-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "C ABI for rapier3d-f64"
publish = false
build = "../build.rs"

[lib]
name = "rapier3d_f64_ffi"
path = "../src/lib.rs"
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
default = ["dim3", "f64"]
dim3 = []
f64 = []
parallel = ["rapier/parallel"]
profiler = ["rapier/profiler"]
enhanced-determinism = ["rapier/enhanced-determinism"]
fem = ["rapier/fem"]

[dependencies]
rapier-c-macros = { path = "../rapier-c-macros" }
rapier = { package = "rapier3d-f64", path = "../../../crates/rapier3d-f64", features = ["serde-serialize", "debug-render"] }
bincode.workspace = true
serde.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(feature, values("dim2", "dim3", "f32", "f64", "robotics"))'] }
