#!/usr/bin/env python3
"""Regenerate the example registry and audit coverage against the Rust testbed."""
from pathlib import Path
import re, json
root=Path(__file__).resolve().parents[3]
target=root/'bindings/c/testbed'
entries=[]
for dim in [2,3]:
    src=(root/f'examples{dim}d/all_examples{dim}.rs').read_text()
    groups=dict(re.findall(r'const (\w+): &str = "([^"]+)";',src))
    out=['/* Generated by update_catalog.py; order matches the Rust testbed. */','#include "testbed.h"']
    rows=[]
    for group,name,fn in re.findall(r'\b([A-Z0-9]+), "([^"]+)", ([\w:]+);',src):
        bits=fn.split('::');stem='/'.join(bits[:-1]);suffix='' if bits[-1]=='run' else '_'+bits[-1]
        ident=stem.replace('/','_')+suffix
        source=f'examples{dim}d/{stem}.rs';port=f'examples{dim}d/{stem}{suffix}.c'
        present=(target/port).exists()
        symbol='tb'+''.join(part[:1].upper()+part[1:] for part in ident.split('_'))
        if present:out.append(f'extern void {symbol}(Testbed *);')
        feature='fem' if 'fem' in stem else 'robotics' if stem in ('urdf3', 'mjcf3', 'mujoco_menagerie3') else None
        entries.append(dict(id=ident,dimension=dim,group=groups[group],name=name,rust=source,c=port if present else None,feature=feature))
        fields=', '.join(json.dumps(x) for x in [ident,groups[group],name,source])
        if present and feature:
            rows.extend([f'#ifdef RAPIER_{feature.upper()}',f'    {{{fields}, {symbol}, NULL}},','#else',f'    {{{fields}, NULL, "Requires RAPIER_FEATURES={feature}"}},','#endif'])
        else:rows.append(f'    {{{fields}, '+(f'{symbol}, NULL' if present else 'NULL, "Port pending"')+'},')
    out+=['const TbExample tbExamples[] = {',*rows,'};','const size_t tbExampleCount=TB_COUNT(tbExamples);']
    (target/f'registry{dim}.c').write_text('\n'.join(out)+'\n')
(target/'coverage.json').write_text(json.dumps(entries,indent=2)+'\n')
print(f'{sum(e["c"] is not None for e in entries)}/{len(entries)} C scene ports')
