/* Generated by update_catalog.py; order matches the Rust testbed. */
#include "testbed.h"
extern void tbAddRemove2(Testbed *);
extern void tbDrum2(Testbed *);
extern void tbInvPyramid2(Testbed *);
extern void tbPlatform2(Testbed *);
extern void tbPyramid2(Testbed *);
extern void tbSensor2(Testbed *);
extern void tbConvexPolygons2(Testbed *);
extern void tbHeightfield2(Testbed *);
extern void tbPolyline2(Testbed *);
extern void tbTrimesh2(Testbed *);
extern void tbVoxels2(Testbed *);
extern void tbCollisionGroups2(Testbed *);
extern void tbOneWayPlatforms2(Testbed *);
extern void tbLockedRotations2(Testbed *);
extern void tbRestitution2(Testbed *);
extern void tbDamping2(Testbed *);
extern void tbCcd2(Testbed *);
extern void tbJoints2(Testbed *);
extern void tbRopeJoints2(Testbed *);
extern void tbPinSlotJoint2(Testbed *);
extern void tbJointMotorPosition2(Testbed *);
extern void tbInverseKinematics2(Testbed *);
extern void tbMultiPendulum2(Testbed *);
extern void tbSoftBodies2(Testbed *);
extern void tbSoftBlobs2(Testbed *);
extern void tbSoftJelly2(Testbed *);
extern void tbSoftSurface2(Testbed *);
extern void tbSoftPile2(Testbed *);
extern void tbSoftThinFeatures2(Testbed *);
extern void tbSoftLetters2(Testbed *);
extern void tbSoftPlasticity2(Testbed *);
extern void tbSoftTearing2(Testbed *);
extern void tbSoftForceTearing2(Testbed *);
extern void tbSoftCutting2(Testbed *);
extern void tbSoftStress2(Testbed *);
extern void tbSoftFem2(Testbed *);
extern void tbSoftJoints2(Testbed *);
extern void tbCharacterController2(Testbed *);
extern void tbDebugAngularLimits2(Testbed *);
extern void tbDebugBoxBall2(Testbed *);
extern void tbDebugCompression2(Testbed *);
extern void tbDebugIntersection2(Testbed *);
extern void tbDebugManyColliders2(Testbed *);
extern void tbDebugTotalOverlap2(Testbed *);
extern void tbDebugVerticalColumn2(Testbed *);
extern void tbDebugSelfIntersect2(Testbed *);
extern void tbS2dHighMassRatio1(Testbed *);
extern void tbS2dHighMassRatio2(Testbed *);
extern void tbS2dHighMassRatio3(Testbed *);
extern void tbS2dConfined(Testbed *);
extern void tbS2dPyramid(Testbed *);
extern void tbS2dCardHouse(Testbed *);
extern void tbS2dArch(Testbed *);
extern void tbS2dBridge(Testbed *);
extern void tbS2dBallAndChain(Testbed *);
extern void tbS2dJointGrid(Testbed *);
extern void tbS2dFarPyramid(Testbed *);
extern void tbB2dCompounds(Testbed *);
extern void tbB2dJointGrid(Testbed *);
extern void tbB2dJunkyard(Testbed *);
extern void tbB2dLargePyramid(Testbed *);
extern void tbB2dManyPyramids(Testbed *);
extern void tbB2dRain(Testbed *);
extern void tbB2dSmash(Testbed *);
extern void tbB2dSpinner(Testbed *);
extern void tbB2dTumbler(Testbed *);
extern void tbB2dWasher(Testbed *);
extern void tbStressTestsBalls2(Testbed *);
extern void tbStressTestsBoxes2(Testbed *);
extern void tbStressTestsCapsules2(Testbed *);
extern void tbStressTestsConvexPolygons2(Testbed *);
extern void tbStressTestsHeightfield2(Testbed *);
extern void tbStressTestsLargePyramids2(Testbed *);
extern void tbStressTestsManyPyramids2(Testbed *);
extern void tbStressTestsPyramid2(Testbed *);
extern void tbStressTestsRagdolls2(Testbed *);
extern void tbStressTestsRopes2(Testbed *);
extern void tbStressTestsVerticalStacks2(Testbed *);
extern void tbStressTestsJointBall2(Testbed *);
extern void tbStressTestsJointFixed2(Testbed *);
extern void tbStressTestsJointPrismatic2(Testbed *);
extern void tbStressTestsSoftBlobs2(Testbed *);
extern void tbStressTestsSoftJellies2(Testbed *);
extern void tbStressTestsSoftRopes2(Testbed *);
extern void tbStressTestsSoftStrips2(Testbed *);
extern void tbStressTestsSoftClothKeva2(Testbed *);
extern void tbStressTestsSoftSlab2(Testbed *);
extern void tbStressTestsSoftFemBeams2(Testbed *);
const TbExample tbExamples[] = {
    {"add_remove2", "Collisions", "Add remove", "examples2d/add_remove2.rs", tbAddRemove2, NULL},
    {"drum2", "Collisions", "Drum", "examples2d/drum2.rs", tbDrum2, NULL},
    {"inv_pyramid2", "Collisions", "Inv pyramid", "examples2d/inv_pyramid2.rs", tbInvPyramid2, NULL},
    {"platform2", "Collisions", "Platform", "examples2d/platform2.rs", tbPlatform2, NULL},
    {"pyramid2", "Collisions", "Pyramid", "examples2d/pyramid2.rs", tbPyramid2, NULL},
    {"sensor2", "Collisions", "Sensor", "examples2d/sensor2.rs", tbSensor2, NULL},
    {"convex_polygons2", "Collisions", "Convex polygons", "examples2d/convex_polygons2.rs", tbConvexPolygons2, NULL},
    {"heightfield2", "Collisions", "Heightfield", "examples2d/heightfield2.rs", tbHeightfield2, NULL},
    {"polyline2", "Collisions", "Polyline", "examples2d/polyline2.rs", tbPolyline2, NULL},
    {"trimesh2", "Collisions", "Trimesh", "examples2d/trimesh2.rs", tbTrimesh2, NULL},
    {"voxels2", "Collisions", "Voxels", "examples2d/voxels2.rs", tbVoxels2, NULL},
    {"collision_groups2", "Collisions", "Collision groups", "examples2d/collision_groups2.rs", tbCollisionGroups2, NULL},
    {"one_way_platforms2", "Collisions", "One-way platforms", "examples2d/one_way_platforms2.rs", tbOneWayPlatforms2, NULL},
    {"locked_rotations2", "Dynamics", "Locked rotations", "examples2d/locked_rotations2.rs", tbLockedRotations2, NULL},
    {"restitution2", "Dynamics", "Restitution", "examples2d/restitution2.rs", tbRestitution2, NULL},
    {"damping2", "Dynamics", "Damping", "examples2d/damping2.rs", tbDamping2, NULL},
    {"ccd2", "Dynamics", "CCD", "examples2d/ccd2.rs", tbCcd2, NULL},
    {"joints2", "Joints", "Joints", "examples2d/joints2.rs", tbJoints2, NULL},
    {"rope_joints2", "Joints", "Rope Joints", "examples2d/rope_joints2.rs", tbRopeJoints2, NULL},
    {"pin_slot_joint2", "Joints", "Pin Slot Joint", "examples2d/pin_slot_joint2.rs", tbPinSlotJoint2, NULL},
    {"joint_motor_position2", "Joints", "Joint motor position", "examples2d/joint_motor_position2.rs", tbJointMotorPosition2, NULL},
    {"inverse_kinematics2", "Joints", "Inverse kinematics", "examples2d/inverse_kinematics2.rs", tbInverseKinematics2, NULL},
    {"multi_pendulum2", "Joints", "Multi Pendulum", "examples2d/multi_pendulum2.rs", tbMultiPendulum2, NULL},
    {"soft_bodies2", "Soft bodies", "Soft bodies", "examples2d/soft_bodies2.rs", tbSoftBodies2, NULL},
    {"soft_blobs2", "Soft bodies", "Blobs", "examples2d/soft_blobs2.rs", tbSoftBlobs2, NULL},
    {"soft_jelly2", "Soft bodies", "Jelly", "examples2d/soft_jelly2.rs", tbSoftJelly2, NULL},
    {"soft_surface2", "Soft bodies", "Deformable polylines", "examples2d/soft_surface2.rs", tbSoftSurface2, NULL},
    {"soft_pile2", "Soft bodies", "Soft pile", "examples2d/soft_pile2.rs", tbSoftPile2, NULL},
    {"soft_thin_features2", "Soft bodies", "Thin features", "examples2d/soft_thin_features2.rs", tbSoftThinFeatures2, NULL},
    {"soft_letters2", "Soft bodies", "Soft letters", "examples2d/soft_letters2.rs", tbSoftLetters2, NULL},
    {"soft_plasticity2", "Soft bodies", "Plasticity", "examples2d/soft_plasticity2.rs", tbSoftPlasticity2, NULL},
    {"soft_tearing2", "Soft bodies", "Tearing", "examples2d/soft_tearing2.rs", tbSoftTearing2, NULL},
    {"soft_force_tearing2", "Soft bodies", "Force tearing", "examples2d/soft_force_tearing2.rs", tbSoftForceTearing2, NULL},
    {"soft_cutting2", "Soft bodies", "Cutting", "examples2d/soft_cutting2.rs", tbSoftCutting2, NULL},
    {"soft_stress2", "Soft bodies", "Stress coloring", "examples2d/soft_stress2.rs", tbSoftStress2, NULL},
#ifdef RAPIER_FEM
    {"soft_fem2", "Soft bodies", "Soft FEM", "examples2d/soft_fem2.rs", tbSoftFem2, NULL},
#else
    {"soft_fem2", "Soft bodies", "Soft FEM", "examples2d/soft_fem2.rs", NULL, "Requires RAPIER_FEATURES=fem"},
#endif
    {"soft_joints2", "Soft bodies", "Soft joints", "examples2d/soft_joints2.rs", tbSoftJoints2, NULL},
    {"character_controller2", "Controls", "Character controller", "examples2d/character_controller2.rs", tbCharacterController2, NULL},
    {"debug_angular_limits2", "Debug", "Angular limits", "examples2d/debug_angular_limits2.rs", tbDebugAngularLimits2, NULL},
    {"debug_box_ball2", "Debug", "Box ball", "examples2d/debug_box_ball2.rs", tbDebugBoxBall2, NULL},
    {"debug_compression2", "Debug", "Compression", "examples2d/debug_compression2.rs", tbDebugCompression2, NULL},
    {"debug_intersection2", "Debug", "Intersection", "examples2d/debug_intersection2.rs", tbDebugIntersection2, NULL},
    {"debug_many_colliders2", "Debug", "Many colliders", "examples2d/debug_many_colliders2.rs", tbDebugManyColliders2, NULL},
    {"debug_total_overlap2", "Debug", "Total overlap", "examples2d/debug_total_overlap2.rs", tbDebugTotalOverlap2, NULL},
    {"debug_vertical_column2", "Debug", "Vertical column", "examples2d/debug_vertical_column2.rs", tbDebugVerticalColumn2, NULL},
    {"debug_self_intersect2", "Debug", "Self intersect", "examples2d/debug_self_intersect2.rs", tbDebugSelfIntersect2, NULL},
    {"s2d_high_mass_ratio_1", "Inspired by Solver 2D", "High mass ratio 1", "examples2d/s2d_high_mass_ratio_1.rs", tbS2dHighMassRatio1, NULL},
    {"s2d_high_mass_ratio_2", "Inspired by Solver 2D", "High mass ratio 2", "examples2d/s2d_high_mass_ratio_2.rs", tbS2dHighMassRatio2, NULL},
    {"s2d_high_mass_ratio_3", "Inspired by Solver 2D", "High mass ratio 3", "examples2d/s2d_high_mass_ratio_3.rs", tbS2dHighMassRatio3, NULL},
    {"s2d_confined", "Inspired by Solver 2D", "Confined", "examples2d/s2d_confined.rs", tbS2dConfined, NULL},
    {"s2d_pyramid", "Inspired by Solver 2D", "Pyramid", "examples2d/s2d_pyramid.rs", tbS2dPyramid, NULL},
    {"s2d_card_house", "Inspired by Solver 2D", "Card house", "examples2d/s2d_card_house.rs", tbS2dCardHouse, NULL},
    {"s2d_arch", "Inspired by Solver 2D", "Arch", "examples2d/s2d_arch.rs", tbS2dArch, NULL},
    {"s2d_bridge", "Inspired by Solver 2D", "Bridge", "examples2d/s2d_bridge.rs", tbS2dBridge, NULL},
    {"s2d_ball_and_chain", "Inspired by Solver 2D", "Ball and chain", "examples2d/s2d_ball_and_chain.rs", tbS2dBallAndChain, NULL},
    {"s2d_joint_grid", "Inspired by Solver 2D", "Joint grid", "examples2d/s2d_joint_grid.rs", tbS2dJointGrid, NULL},
    {"s2d_far_pyramid", "Inspired by Solver 2D", "Far pyramid", "examples2d/s2d_far_pyramid.rs", tbS2dFarPyramid, NULL},
    {"b2d_compounds", "Third-party benchmarks", "Compounds", "examples2d/b2d_compounds.rs", tbB2dCompounds, NULL},
    {"b2d_joint_grid", "Third-party benchmarks", "Joint grid", "examples2d/b2d_joint_grid.rs", tbB2dJointGrid, NULL},
    {"b2d_junkyard", "Third-party benchmarks", "Junkyard", "examples2d/b2d_junkyard.rs", tbB2dJunkyard, NULL},
    {"b2d_large_pyramid", "Third-party benchmarks", "Large pyramid", "examples2d/b2d_large_pyramid.rs", tbB2dLargePyramid, NULL},
    {"b2d_many_pyramids", "Third-party benchmarks", "Many pyramids", "examples2d/b2d_many_pyramids.rs", tbB2dManyPyramids, NULL},
    {"b2d_rain", "Third-party benchmarks", "Rain", "examples2d/b2d_rain.rs", tbB2dRain, NULL},
    {"b2d_smash", "Third-party benchmarks", "Smash", "examples2d/b2d_smash.rs", tbB2dSmash, NULL},
    {"b2d_spinner", "Third-party benchmarks", "Spinner", "examples2d/b2d_spinner.rs", tbB2dSpinner, NULL},
    {"b2d_tumbler", "Third-party benchmarks", "Tumbler", "examples2d/b2d_tumbler.rs", tbB2dTumbler, NULL},
    {"b2d_washer", "Third-party benchmarks", "Washer", "examples2d/b2d_washer.rs", tbB2dWasher, NULL},
    {"stress_tests_balls2", "Stress tests", "Balls", "examples2d/stress_tests/balls2.rs", tbStressTestsBalls2, NULL},
    {"stress_tests_boxes2", "Stress tests", "Boxes", "examples2d/stress_tests/boxes2.rs", tbStressTestsBoxes2, NULL},
    {"stress_tests_capsules2", "Stress tests", "Capsules", "examples2d/stress_tests/capsules2.rs", tbStressTestsCapsules2, NULL},
    {"stress_tests_convex_polygons2", "Stress tests", "Convex polygons", "examples2d/stress_tests/convex_polygons2.rs", tbStressTestsConvexPolygons2, NULL},
    {"stress_tests_heightfield2", "Stress tests", "Heightfield", "examples2d/stress_tests/heightfield2.rs", tbStressTestsHeightfield2, NULL},
    {"stress_tests_large_pyramids2", "Stress tests", "Large pyramids", "examples2d/stress_tests/large_pyramids2.rs", tbStressTestsLargePyramids2, NULL},
    {"stress_tests_many_pyramids2", "Stress tests", "Many pyramids", "examples2d/stress_tests/many_pyramids2.rs", tbStressTestsManyPyramids2, NULL},
    {"stress_tests_pyramid2", "Stress tests", "Pyramid", "examples2d/stress_tests/pyramid2.rs", tbStressTestsPyramid2, NULL},
    {"stress_tests_ragdolls2", "Stress tests", "Ragdoll piles", "examples2d/stress_tests/ragdolls2.rs", tbStressTestsRagdolls2, NULL},
    {"stress_tests_ropes2", "Stress tests", "Ropes", "examples2d/stress_tests/ropes2.rs", tbStressTestsRopes2, NULL},
    {"stress_tests_vertical_stacks2", "Stress tests", "Verticals stacks", "examples2d/stress_tests/vertical_stacks2.rs", tbStressTestsVerticalStacks2, NULL},
    {"stress_tests_joint_ball2", "Stress tests", "(Stress test) joint ball", "examples2d/stress_tests/joint_ball2.rs", tbStressTestsJointBall2, NULL},
    {"stress_tests_joint_fixed2", "Stress tests", "(Stress test) joint fixed", "examples2d/stress_tests/joint_fixed2.rs", tbStressTestsJointFixed2, NULL},
    {"stress_tests_joint_prismatic2", "Stress tests", "(Stress test) joint prismatic", "examples2d/stress_tests/joint_prismatic2.rs", tbStressTestsJointPrismatic2, NULL},
    {"stress_tests_soft_blobs2", "Stress tests", "Soft blobs", "examples2d/stress_tests/soft_blobs2.rs", tbStressTestsSoftBlobs2, NULL},
    {"stress_tests_soft_jellies2", "Stress tests", "Soft jellies", "examples2d/stress_tests/soft_jellies2.rs", tbStressTestsSoftJellies2, NULL},
    {"stress_tests_soft_ropes2", "Stress tests", "Soft ropes", "examples2d/stress_tests/soft_ropes2.rs", tbStressTestsSoftRopes2, NULL},
    {"stress_tests_soft_strips2", "Stress tests", "Soft strips", "examples2d/stress_tests/soft_strips2.rs", tbStressTestsSoftStrips2, NULL},
    {"stress_tests_soft_cloth_keva2", "Stress tests", "Soft cloth on Keva tower", "examples2d/stress_tests/soft_cloth_keva2.rs", tbStressTestsSoftClothKeva2, NULL},
    {"stress_tests_soft_slab2", "Stress tests", "Soft slab shower", "examples2d/stress_tests/soft_slab2.rs", tbStressTestsSoftSlab2, NULL},
#ifdef RAPIER_FEM
    {"stress_tests_soft_fem_beams2", "Stress tests", "Soft FEM beams", "examples2d/stress_tests/soft_fem_beams2.rs", tbStressTestsSoftFemBeams2, NULL},
#else
    {"stress_tests_soft_fem_beams2", "Stress tests", "Soft FEM beams", "examples2d/stress_tests/soft_fem_beams2.rs", NULL, "Requires RAPIER_FEATURES=fem"},
#endif
};
const size_t tbExampleCount=TB_COUNT(tbExamples);
