/* Generated by update_catalog.py; order matches the Rust testbed. */
#include "testbed.h"
extern void tbFountain3(Testbed *);
extern void tbPrimitives3(Testbed *);
extern void tbKeva3(Testbed *);
extern void tbNewtonCradle3(Testbed *);
extern void tbDomino3(Testbed *);
extern void tbPlatform3(Testbed *);
extern void tbSensor3(Testbed *);
extern void tbCompound3(Testbed *);
extern void tbConvexDecomposition3(Testbed *);
extern void tbConvexPolyhedron3(Testbed *);
extern void tbTrimesh3(Testbed *);
extern void tbDynamicTrimesh3(Testbed *);
extern void tbHeightfield3(Testbed *);
extern void tbVoxels3(Testbed *);
extern void tbCollisionGroups3(Testbed *);
extern void tbOneWayPlatforms3(Testbed *);
extern void tbLockedRotations3(Testbed *);
extern void tbRestitution3(Testbed *);
extern void tbDamping3(Testbed *);
extern void tbGyroscopic3(Testbed *);
extern void tbCcd3(Testbed *);
extern void tbJoints3RunImpulseJoints(Testbed *);
extern void tbJoints3RunMultibodyJoints(Testbed *);
extern void tbRopeJoints3(Testbed *);
extern void tbSpringJoints3(Testbed *);
extern void tbJointMotorPosition3(Testbed *);
extern void tbInverseKinematics3(Testbed *);
extern void tbSoftBodies3(Testbed *);
extern void tbSoftCloth3(Testbed *);
extern void tbSoftJelly3(Testbed *);
extern void tbSoftJoints3(Testbed *);
extern void tbSoftMeshes3(Testbed *);
extern void tbSoftSurface3(Testbed *);
extern void tbSoftPile3(Testbed *);
extern void tbSoftThinFeatures3(Testbed *);
extern void tbSoftClothStress3(Testbed *);
extern void tbSoftPlasticity3(Testbed *);
extern void tbSoftTearing3(Testbed *);
extern void tbSoftDress3(Testbed *);
extern void tbSoftFem3(Testbed *);
extern void tbSoftTrimesh3(Testbed *);
extern void tbCharacterController3(Testbed *);
extern void tbVehicleController3(Testbed *);
extern void tbVehicleJoints3(Testbed *);
extern void tbUrdf3(Testbed *);
extern void tbMjcf3(Testbed *);
extern void tbMujocoMenagerie3(Testbed *);
extern void tbDebugAngularLimits3(Testbed *);
extern void tbDebugArticulations3(Testbed *);
extern void tbDebugAddRemoveCollider3(Testbed *);
extern void tbDebugMultiColliderBody3(Testbed *);
extern void tbDebugBigColliders3(Testbed *);
extern void tbDebugBoxes3(Testbed *);
extern void tbDebugBalls3(Testbed *);
extern void tbDebugDisabled3(Testbed *);
extern void tbDebugTwoCubes3(Testbed *);
extern void tbDebugPop3(Testbed *);
extern void tbDebugDynamicColliderAdd3(Testbed *);
extern void tbDebugFriction3(Testbed *);
extern void tbDebugInternalEdges3(Testbed *);
extern void tbDebugSelfIntersect3(Testbed *);
extern void tbDebugLongChain3(Testbed *);
extern void tbDebugChainHighMassRatio3(Testbed *);
extern void tbDebugCubeHighMassRatio3(Testbed *);
extern void tbDebugTriangle3(Testbed *);
extern void tbDebugTrimesh3(Testbed *);
extern void tbDebugThinCubeOnMesh3(Testbed *);
extern void tbDebugCylinder3(Testbed *);
extern void tbDebugInfiniteFall3(Testbed *);
extern void tbDebugPrismatic3(Testbed *);
extern void tbDebugRollback3(Testbed *);
extern void tbDebugShapeModification3(Testbed *);
extern void tbDebugSleepingKinematic3(Testbed *);
extern void tbDebugDeserialize3(Testbed *);
extern void tbDebugMultibodyAngMotorPos3(Testbed *);
extern void tbStressTestsBalls3(Testbed *);
extern void tbStressTestsBoxes3(Testbed *);
extern void tbStressTestsCapsules3(Testbed *);
extern void tbStressTestsCcd3(Testbed *);
extern void tbStressTestsCompound3(Testbed *);
extern void tbStressTestsConvexPolyhedron3(Testbed *);
extern void tbStressTestsManyKinematics3(Testbed *);
extern void tbStressTestsManyStatic3(Testbed *);
extern void tbStressTestsManySleep3(Testbed *);
extern void tbStressTestsHeightfield3(Testbed *);
extern void tbStressTestsStacks3(Testbed *);
extern void tbStressTestsPyramid3(Testbed *);
extern void tbStressTestsTrimesh3(Testbed *);
extern void tbStressTestsJointBall3(Testbed *);
extern void tbStressTestsJointFixed3(Testbed *);
extern void tbStressTestsJointRevolute3(Testbed *);
extern void tbStressTestsJointPrismatic3(Testbed *);
extern void tbStressTestsRagdolls3(Testbed *);
extern void tbStressTestsRopes3(Testbed *);
extern void tbStressTestsManyPyramids3(Testbed *);
extern void tbStressTestsKeva3(Testbed *);
extern void tbStressTestsRayCast3(Testbed *);
extern void tbStressTestsSoftBlobs3(Testbed *);
extern void tbStressTestsSoftJellies3(Testbed *);
extern void tbStressTestsSoftRopes3(Testbed *);
extern void tbStressTestsSoftClothDrape3(Testbed *);
extern void tbStressTestsSoftClothKeva3(Testbed *);
extern void tbStressTestsSoftSlab3(Testbed *);
extern void tbStressTestsSoftFemBeams3(Testbed *);
extern void tbB3dLargePyramid(Testbed *);
extern void tbB3dManyPyramids(Testbed *);
extern void tbB3dJointGrid(Testbed *);
extern void tbB3dJunkyard(Testbed *);
extern void tbB3dWasher(Testbed *);
extern void tbB3dTreesRun100(Testbed *);
extern void tbB3dTreesRun50(Testbed *);
extern void tbB3dTreesRun25(Testbed *);
extern void tbB3dRain(Testbed *);
extern void tbB3dLargeWorld(Testbed *);
const TbExample tbExamples[] = {
    {"fountain3", "Collisions", "Fountain", "examples3d/fountain3.rs", tbFountain3, NULL},
    {"primitives3", "Collisions", "Primitives", "examples3d/primitives3.rs", tbPrimitives3, NULL},
    {"keva3", "Collisions", "Keva tower", "examples3d/keva3.rs", tbKeva3, NULL},
    {"newton_cradle3", "Collisions", "Newton cradle", "examples3d/newton_cradle3.rs", tbNewtonCradle3, NULL},
    {"domino3", "Collisions", "Domino", "examples3d/domino3.rs", tbDomino3, NULL},
    {"platform3", "Collisions", "Platform", "examples3d/platform3.rs", tbPlatform3, NULL},
    {"sensor3", "Collisions", "Sensor", "examples3d/sensor3.rs", tbSensor3, NULL},
    {"compound3", "Collisions", "Compound", "examples3d/compound3.rs", tbCompound3, NULL},
    {"convex_decomposition3", "Collisions", "Convex decomposition", "examples3d/convex_decomposition3.rs", tbConvexDecomposition3, NULL},
    {"convex_polyhedron3", "Collisions", "Convex polyhedron", "examples3d/convex_polyhedron3.rs", tbConvexPolyhedron3, NULL},
    {"trimesh3", "Collisions", "TriMesh", "examples3d/trimesh3.rs", tbTrimesh3, NULL},
    {"dynamic_trimesh3", "Collisions", "Dynamic trimeshes", "examples3d/dynamic_trimesh3.rs", tbDynamicTrimesh3, NULL},
    {"heightfield3", "Collisions", "Heightfield", "examples3d/heightfield3.rs", tbHeightfield3, NULL},
    {"voxels3", "Collisions", "Voxels", "examples3d/voxels3.rs", tbVoxels3, NULL},
    {"collision_groups3", "Collisions", "Collision groups", "examples3d/collision_groups3.rs", tbCollisionGroups3, NULL},
    {"one_way_platforms3", "Collisions", "One-way platforms", "examples3d/one_way_platforms3.rs", tbOneWayPlatforms3, NULL},
    {"locked_rotations3", "Dynamics", "Locked rotations", "examples3d/locked_rotations3.rs", tbLockedRotations3, NULL},
    {"restitution3", "Dynamics", "Restitution", "examples3d/restitution3.rs", tbRestitution3, NULL},
    {"damping3", "Dynamics", "Damping", "examples3d/damping3.rs", tbDamping3, NULL},
    {"gyroscopic3", "Dynamics", "Gyroscopic", "examples3d/gyroscopic3.rs", tbGyroscopic3, NULL},
    {"ccd3", "Dynamics", "CCD", "examples3d/ccd3.rs", tbCcd3, NULL},
    {"joints3_run_impulse_joints", "Joints", "Impulse Joints", "examples3d/joints3.rs", tbJoints3RunImpulseJoints, NULL},
    {"joints3_run_multibody_joints", "Joints", "Multibody Joints", "examples3d/joints3.rs", tbJoints3RunMultibodyJoints, NULL},
    {"rope_joints3", "Joints", "Rope Joints", "examples3d/rope_joints3.rs", tbRopeJoints3, NULL},
    {"spring_joints3", "Joints", "Spring Joints", "examples3d/spring_joints3.rs", tbSpringJoints3, NULL},
    {"joint_motor_position3", "Joints", "Joint Motor Position", "examples3d/joint_motor_position3.rs", tbJointMotorPosition3, NULL},
    {"inverse_kinematics3", "Joints", "Inverse kinematics", "examples3d/inverse_kinematics3.rs", tbInverseKinematics3, NULL},
    {"soft_bodies3", "Soft bodies", "Soft bodies", "examples3d/soft_bodies3.rs", tbSoftBodies3, NULL},
    {"soft_cloth3", "Soft bodies", "Cloth", "examples3d/soft_cloth3.rs", tbSoftCloth3, NULL},
    {"soft_jelly3", "Soft bodies", "Jelly", "examples3d/soft_jelly3.rs", tbSoftJelly3, NULL},
    {"soft_joints3", "Soft bodies", "Soft joints", "examples3d/soft_joints3.rs", tbSoftJoints3, NULL},
    {"soft_meshes3", "Soft bodies", "Cluster meshes", "examples3d/soft_meshes3.rs", tbSoftMeshes3, NULL},
    {"soft_surface3", "Soft bodies", "Deformable trimeshes", "examples3d/soft_surface3.rs", tbSoftSurface3, NULL},
    {"soft_pile3", "Soft bodies", "Soft pile", "examples3d/soft_pile3.rs", tbSoftPile3, NULL},
    {"soft_thin_features3", "Soft bodies", "Thin features", "examples3d/soft_thin_features3.rs", tbSoftThinFeatures3, NULL},
    {"soft_cloth_stress3", "Soft bodies", "Cloth stress", "examples3d/soft_cloth_stress3.rs", tbSoftClothStress3, NULL},
    {"soft_plasticity3", "Soft bodies", "Plasticity", "examples3d/soft_plasticity3.rs", tbSoftPlasticity3, NULL},
    {"soft_tearing3", "Soft bodies", "Tearing", "examples3d/soft_tearing3.rs", tbSoftTearing3, NULL},
    {"soft_dress3", "Soft bodies", "Dancing dress", "examples3d/soft_dress3.rs", tbSoftDress3, NULL},
#ifdef RAPIER_FEM
    {"soft_fem3", "Soft bodies", "Soft FEM", "examples3d/soft_fem3.rs", tbSoftFem3, NULL},
#else
    {"soft_fem3", "Soft bodies", "Soft FEM", "examples3d/soft_fem3.rs", NULL, "Requires RAPIER_FEATURES=fem"},
#endif
    {"soft_trimesh3", "Soft bodies", "Soft trimeshes", "examples3d/soft_trimesh3.rs", tbSoftTrimesh3, NULL},
    {"character_controller3", "Controls", "Character controller", "examples3d/character_controller3.rs", tbCharacterController3, NULL},
    {"vehicle_controller3", "Controls", "Vehicle controller", "examples3d/vehicle_controller3.rs", tbVehicleController3, NULL},
    {"vehicle_joints3", "Controls", "Vehicle joints", "examples3d/vehicle_joints3.rs", tbVehicleJoints3, NULL},
#ifdef RAPIER_ROBOTICS
    {"urdf3", "Robotics", "URDF", "examples3d/urdf3.rs", tbUrdf3, NULL},
#else
    {"urdf3", "Robotics", "URDF", "examples3d/urdf3.rs", NULL, "Requires RAPIER_FEATURES=robotics"},
#endif
#ifdef RAPIER_ROBOTICS
    {"mjcf3", "Robotics", "MJCF", "examples3d/mjcf3.rs", tbMjcf3, NULL},
#else
    {"mjcf3", "Robotics", "MJCF", "examples3d/mjcf3.rs", NULL, "Requires RAPIER_FEATURES=robotics"},
#endif
#ifdef RAPIER_ROBOTICS
    {"mujoco_menagerie3", "Robotics", "Mujoco Menagerie", "examples3d/mujoco_menagerie3.rs", tbMujocoMenagerie3, NULL},
#else
    {"mujoco_menagerie3", "Robotics", "Mujoco Menagerie", "examples3d/mujoco_menagerie3.rs", NULL, "Requires RAPIER_FEATURES=robotics"},
#endif
    {"debug_angular_limits3", "Debug", "Angular limits", "examples3d/debug_angular_limits3.rs", tbDebugAngularLimits3, NULL},
    {"debug_articulations3", "Debug", "Multibody joints", "examples3d/debug_articulations3.rs", tbDebugArticulations3, NULL},
    {"debug_add_remove_collider3", "Debug", "Add/rm collider", "examples3d/debug_add_remove_collider3.rs", tbDebugAddRemoveCollider3, NULL},
    {"debug_multi_collider_body3", "Debug", "Multi-collider body", "examples3d/debug_multi_collider_body3.rs", tbDebugMultiColliderBody3, NULL},
    {"debug_big_colliders3", "Debug", "Big colliders", "examples3d/debug_big_colliders3.rs", tbDebugBigColliders3, NULL},
    {"debug_boxes3", "Debug", "Boxes", "examples3d/debug_boxes3.rs", tbDebugBoxes3, NULL},
    {"debug_balls3", "Debug", "Balls", "examples3d/debug_balls3.rs", tbDebugBalls3, NULL},
    {"debug_disabled3", "Debug", "Disabled", "examples3d/debug_disabled3.rs", tbDebugDisabled3, NULL},
    {"debug_two_cubes3", "Debug", "Two cubes", "examples3d/debug_two_cubes3.rs", tbDebugTwoCubes3, NULL},
    {"debug_pop3", "Debug", "Pop", "examples3d/debug_pop3.rs", tbDebugPop3, NULL},
    {"debug_dynamic_collider_add3", "Debug", "Dyn. collider add", "examples3d/debug_dynamic_collider_add3.rs", tbDebugDynamicColliderAdd3, NULL},
    {"debug_friction3", "Debug", "Friction", "examples3d/debug_friction3.rs", tbDebugFriction3, NULL},
    {"debug_internal_edges3", "Debug", "Internal edges", "examples3d/debug_internal_edges3.rs", tbDebugInternalEdges3, NULL},
    {"debug_self_intersect3", "Debug", "Self intersect", "examples3d/debug_self_intersect3.rs", tbDebugSelfIntersect3, NULL},
    {"debug_long_chain3", "Debug", "Long chain", "examples3d/debug_long_chain3.rs", tbDebugLongChain3, NULL},
    {"debug_chain_high_mass_ratio3", "Debug", "High mass ratio: chain", "examples3d/debug_chain_high_mass_ratio3.rs", tbDebugChainHighMassRatio3, NULL},
    {"debug_cube_high_mass_ratio3", "Debug", "High mass ratio: cube", "examples3d/debug_cube_high_mass_ratio3.rs", tbDebugCubeHighMassRatio3, NULL},
    {"debug_triangle3", "Debug", "Triangle", "examples3d/debug_triangle3.rs", tbDebugTriangle3, NULL},
    {"debug_trimesh3", "Debug", "Trimesh", "examples3d/debug_trimesh3.rs", tbDebugTrimesh3, NULL},
    {"debug_thin_cube_on_mesh3", "Debug", "Thin cube", "examples3d/debug_thin_cube_on_mesh3.rs", tbDebugThinCubeOnMesh3, NULL},
    {"debug_cylinder3", "Debug", "Cylinder", "examples3d/debug_cylinder3.rs", tbDebugCylinder3, NULL},
    {"debug_infinite_fall3", "Debug", "Infinite fall", "examples3d/debug_infinite_fall3.rs", tbDebugInfiniteFall3, NULL},
    {"debug_prismatic3", "Debug", "Prismatic", "examples3d/debug_prismatic3.rs", tbDebugPrismatic3, NULL},
    {"debug_rollback3", "Debug", "Rollback", "examples3d/debug_rollback3.rs", tbDebugRollback3, NULL},
    {"debug_shape_modification3", "Debug", "Shape modification", "examples3d/debug_shape_modification3.rs", tbDebugShapeModification3, NULL},
    {"debug_sleeping_kinematic3", "Debug", "Sleeping kinematics", "examples3d/debug_sleeping_kinematic3.rs", tbDebugSleepingKinematic3, NULL},
    {"debug_deserialize3", "Debug", "Deserialize", "examples3d/debug_deserialize3.rs", tbDebugDeserialize3, NULL},
    {"debug_multibody_ang_motor_pos3", "Debug", "Multibody ang. motor pos.", "examples3d/debug_multibody_ang_motor_pos3.rs", tbDebugMultibodyAngMotorPos3, NULL},
    {"stress_tests_balls3", "Stress tests", "Balls", "examples3d/stress_tests/balls3.rs", tbStressTestsBalls3, NULL},
    {"stress_tests_boxes3", "Stress tests", "Boxes", "examples3d/stress_tests/boxes3.rs", tbStressTestsBoxes3, NULL},
    {"stress_tests_capsules3", "Stress tests", "Capsules", "examples3d/stress_tests/capsules3.rs", tbStressTestsCapsules3, NULL},
    {"stress_tests_ccd3", "Stress tests", "CCD", "examples3d/stress_tests/ccd3.rs", tbStressTestsCcd3, NULL},
    {"stress_tests_compound3", "Stress tests", "Compound", "examples3d/stress_tests/compound3.rs", tbStressTestsCompound3, NULL},
    {"stress_tests_convex_polyhedron3", "Stress tests", "Convex polyhedron", "examples3d/stress_tests/convex_polyhedron3.rs", tbStressTestsConvexPolyhedron3, NULL},
    {"stress_tests_many_kinematics3", "Stress tests", "Many kinematics", "examples3d/stress_tests/many_kinematics3.rs", tbStressTestsManyKinematics3, NULL},
    {"stress_tests_many_static3", "Stress tests", "Many static", "examples3d/stress_tests/many_static3.rs", tbStressTestsManyStatic3, NULL},
    {"stress_tests_many_sleep3", "Stress tests", "Many sleep", "examples3d/stress_tests/many_sleep3.rs", tbStressTestsManySleep3, NULL},
    {"stress_tests_heightfield3", "Stress tests", "Heightfield", "examples3d/stress_tests/heightfield3.rs", tbStressTestsHeightfield3, NULL},
    {"stress_tests_stacks3", "Stress tests", "Stacks", "examples3d/stress_tests/stacks3.rs", tbStressTestsStacks3, NULL},
    {"stress_tests_pyramid3", "Stress tests", "Pyramid", "examples3d/stress_tests/pyramid3.rs", tbStressTestsPyramid3, NULL},
    {"stress_tests_trimesh3", "Stress tests", "Trimesh", "examples3d/stress_tests/trimesh3.rs", tbStressTestsTrimesh3, NULL},
    {"stress_tests_joint_ball3", "Stress tests", "ImpulseJoint ball", "examples3d/stress_tests/joint_ball3.rs", tbStressTestsJointBall3, NULL},
    {"stress_tests_joint_fixed3", "Stress tests", "ImpulseJoint fixed", "examples3d/stress_tests/joint_fixed3.rs", tbStressTestsJointFixed3, NULL},
    {"stress_tests_joint_revolute3", "Stress tests", "ImpulseJoint revolute", "examples3d/stress_tests/joint_revolute3.rs", tbStressTestsJointRevolute3, NULL},
    {"stress_tests_joint_prismatic3", "Stress tests", "ImpulseJoint prismatic", "examples3d/stress_tests/joint_prismatic3.rs", tbStressTestsJointPrismatic3, NULL},
    {"stress_tests_ragdolls3", "Stress tests", "Ragdoll piles", "examples3d/stress_tests/ragdolls3.rs", tbStressTestsRagdolls3, NULL},
    {"stress_tests_ropes3", "Stress tests", "Ropes", "examples3d/stress_tests/ropes3.rs", tbStressTestsRopes3, NULL},
    {"stress_tests_many_pyramids3", "Stress tests", "Many pyramids", "examples3d/stress_tests/many_pyramids3.rs", tbStressTestsManyPyramids3, NULL},
    {"stress_tests_keva3", "Stress tests", "Keva tower", "examples3d/stress_tests/keva3.rs", tbStressTestsKeva3, NULL},
    {"stress_tests_ray_cast3", "Stress tests", "Ray cast", "examples3d/stress_tests/ray_cast3.rs", tbStressTestsRayCast3, NULL},
    {"stress_tests_soft_blobs3", "Stress tests", "Soft blobs", "examples3d/stress_tests/soft_blobs3.rs", tbStressTestsSoftBlobs3, NULL},
    {"stress_tests_soft_jellies3", "Stress tests", "Soft jellies", "examples3d/stress_tests/soft_jellies3.rs", tbStressTestsSoftJellies3, NULL},
    {"stress_tests_soft_ropes3", "Stress tests", "Soft ropes", "examples3d/stress_tests/soft_ropes3.rs", tbStressTestsSoftRopes3, NULL},
    {"stress_tests_soft_cloth_drape3", "Stress tests", "Soft cloth drape", "examples3d/stress_tests/soft_cloth_drape3.rs", tbStressTestsSoftClothDrape3, NULL},
    {"stress_tests_soft_cloth_keva3", "Stress tests", "Soft cloth on Keva tower", "examples3d/stress_tests/soft_cloth_keva3.rs", tbStressTestsSoftClothKeva3, NULL},
    {"stress_tests_soft_slab3", "Stress tests", "Soft slab shower", "examples3d/stress_tests/soft_slab3.rs", tbStressTestsSoftSlab3, NULL},
#ifdef RAPIER_FEM
    {"stress_tests_soft_fem_beams3", "Stress tests", "Soft FEM beams", "examples3d/stress_tests/soft_fem_beams3.rs", tbStressTestsSoftFemBeams3, NULL},
#else
    {"stress_tests_soft_fem_beams3", "Stress tests", "Soft FEM beams", "examples3d/stress_tests/soft_fem_beams3.rs", NULL, "Requires RAPIER_FEATURES=fem"},
#endif
    {"b3d_large_pyramid", "Third-party benchmarks", "Large pyramid", "examples3d/b3d_large_pyramid.rs", tbB3dLargePyramid, NULL},
    {"b3d_many_pyramids", "Third-party benchmarks", "Many pyramids", "examples3d/b3d_many_pyramids.rs", tbB3dManyPyramids, NULL},
    {"b3d_joint_grid", "Third-party benchmarks", "Joint grid", "examples3d/b3d_joint_grid.rs", tbB3dJointGrid, NULL},
    {"b3d_junkyard", "Third-party benchmarks", "Junkyard", "examples3d/b3d_junkyard.rs", tbB3dJunkyard, NULL},
    {"b3d_washer", "Third-party benchmarks", "Washer", "examples3d/b3d_washer.rs", tbB3dWasher, NULL},
    {"b3d_trees_run100", "Third-party benchmarks", "Trees 100", "examples3d/b3d_trees.rs", tbB3dTreesRun100, NULL},
    {"b3d_trees_run50", "Third-party benchmarks", "Trees 50", "examples3d/b3d_trees.rs", tbB3dTreesRun50, NULL},
    {"b3d_trees_run25", "Third-party benchmarks", "Trees 25", "examples3d/b3d_trees.rs", tbB3dTreesRun25, NULL},
    {"b3d_rain", "Third-party benchmarks", "Rain", "examples3d/b3d_rain.rs", tbB3dRain, NULL},
    {"b3d_large_world", "Third-party benchmarks", "Large world", "examples3d/b3d_large_world.rs", tbB3dLargeWorld, NULL},
};
const size_t tbExampleCount=TB_COUNT(tbExamples);
