"""Type stubs for the `rapier3d` package: the Rapier physics engine (3D, f32).

Every public class and function of the compiled extension (`rapier3d._rapier3d`) is
re-exported here, with the pure-Python protocols and the `math` / `loaders` submodules.
"""

from . import loaders as loaders
from . import math as math
from ._debug_render import DebugRenderBackend as DebugRenderBackend
from ._event_handler import EventHandler as EventHandler
from ._event_handler import PhysicsHooks as PhysicsHooks
from ._rapier3d import (
    Vec3 as Vec3,
    Point3 as Point3,
    Rotation3 as Rotation3,
    Quaternion as Quaternion,
    Isometry3 as Isometry3,
    AngVector3 as AngVector3,
    rotation_from_angle as rotation_from_angle,
    RapierError as RapierError,
    InvalidHandle as InvalidHandle,
    MeshConversionError as MeshConversionError,
    UrdfError as UrdfError,
    MjcfError as MjcfError,
    SerializationError as SerializationError,
    QueryFailure as QueryFailure,
    MeshLoaderError as MeshLoaderError,
    RigidBody as RigidBody,
    RigidBodyBuilder as RigidBodyBuilder,
    RigidBodyHandle as RigidBodyHandle,
    RigidBodySet as RigidBodySet,
    RigidBodyType as RigidBodyType,
    LockedAxes as LockedAxes,
    RigidBodyActivation as RigidBodyActivation,
    RigidBodyDamping as RigidBodyDamping,
    RigidBodyDominance as RigidBodyDominance,
    RigidBodyCcd as RigidBodyCcd,
    RigidBodyVelocity as RigidBodyVelocity,
    RigidBodyForces as RigidBodyForces,
    RigidBodyMassProps as RigidBodyMassProps,
    RigidBodyPosition as RigidBodyPosition,
    RigidBodyAdditionalMassProps as RigidBodyAdditionalMassProps,
    MassProperties as MassProperties,
    IntegrationParameters as IntegrationParameters,
    SpringCoefficients as SpringCoefficients,
    CoefficientCombineRule as CoefficientCombineRule,
    FrictionModel as FrictionModel,
    IslandManager as IslandManager,
    CCDSolver as CCDSolver,
    ImpulseJointSet as ImpulseJointSet,
    MultibodyJointSet as MultibodyJointSet,
    SoftBindingError as SoftBindingError,
    SoftBodyHandle as SoftBodyHandle,
    SoftBodyCellModel as SoftBodyCellModel,
    SoftEdgePlasticFlow as SoftEdgePlasticFlow,
    SoftBodyEdgeKind as SoftBodyEdgeKind,
    SoftPatchConstraints as SoftPatchConstraints,
    SoftBodySolver as SoftBodySolver,
    SoftBodyMaterial as SoftBodyMaterial,
    SoftBodyParticleSettings as SoftBodyParticleSettings,
    SoftRecoverySettings as SoftRecoverySettings,
    SoftFemParameters as SoftFemParameters,
    SoftBodiesSettings as SoftBodiesSettings,
    MeshEnclosure as MeshEnclosure,
    VolumeMeshParameters as VolumeMeshParameters,
    SoftBodyBuilder as SoftBodyBuilder,
    SoftBodyParticle as SoftBodyParticle,
    SoftBodyEdge as SoftBodyEdge,
    SoftBodyDihedral as SoftBodyDihedral,
    SoftBodyCell as SoftBodyCell,
    SoftParticleAttachment as SoftParticleAttachment,
    SoftVolumePiece as SoftVolumePiece,
    SoftBodyCluster as SoftBodyCluster,
    SoftMeshId as SoftMeshId,
    SoftMeshRef as SoftMeshRef,
    SoftCollisionMesh as SoftCollisionMesh,
    SoftMeshBinding as SoftMeshBinding,
    SoftBodyPiece as SoftBodyPiece,
    SoftClusterSplit as SoftClusterSplit,
    SoftJointMove as SoftJointMove,
    SoftBodyTearEvent as SoftBodyTearEvent,
    SoftBody as SoftBody,
    SoftBodySet as SoftBodySet,
    JointEnabled as JointEnabled,
    MotorModel as MotorModel,
    JointLimits as JointLimits,
    JointMotor as JointMotor,
    JointAxesMask as JointAxesMask,
    JointAxis as JointAxis,
    ImpulseJointHandle as ImpulseJointHandle,
    MultibodyJointHandle as MultibodyJointHandle,
    MultibodyIndex as MultibodyIndex,
    MultibodyLinkId as MultibodyLinkId,
    InverseKinematicsOption as InverseKinematicsOption,
    FixedJoint as FixedJoint,
    FixedJointBuilder as FixedJointBuilder,
    RevoluteJoint as RevoluteJoint,
    RevoluteJointBuilder as RevoluteJointBuilder,
    PrismaticJoint as PrismaticJoint,
    PrismaticJointBuilder as PrismaticJointBuilder,
    SphericalJoint as SphericalJoint,
    SphericalJointBuilder as SphericalJointBuilder,
    RopeJoint as RopeJoint,
    RopeJointBuilder as RopeJointBuilder,
    SpringJoint as SpringJoint,
    SpringJointBuilder as SpringJointBuilder,
    GenericJoint as GenericJoint,
    GenericJointBuilder as GenericJointBuilder,
    ImpulseJoint as ImpulseJoint,
    MultibodyLink as MultibodyLink,
    Multibody as Multibody,
    MultibodyJoint as MultibodyJoint,
    Collider as Collider,
    ColliderBuilder as ColliderBuilder,
    ColliderHandle as ColliderHandle,
    ColliderSet as ColliderSet,
    ColliderType as ColliderType,
    ColliderEnabled as ColliderEnabled,
    ColliderMaterial as ColliderMaterial,
    ColliderFlags as ColliderFlags,
    ColliderParent as ColliderParent,
    ColliderPosition as ColliderPosition,
    ColliderMassProps as ColliderMassProps,
    ShapeType as ShapeType,
    SharedShape as SharedShape,
    Ball as Ball,
    Cuboid as Cuboid,
    Capsule as Capsule,
    Triangle as Triangle,
    TriMesh as TriMesh,
    HeightField as HeightField,
    Compound as Compound,
    Voxels as Voxels,
    FillMode as FillMode,
    Cylinder as Cylinder,
    Cone as Cone,
    ConvexPolyhedron as ConvexPolyhedron,
    Aabb as Aabb,
    BoundingSphere as BoundingSphere,
    MeshConverter as MeshConverter,
    TriMeshFlags as TriMeshFlags,
    ActiveEvents as ActiveEvents,
    ActiveHooks as ActiveHooks,
    ActiveCollisionTypes as ActiveCollisionTypes,
    Group as Group,
    InteractionTestMode as InteractionTestMode,
    InteractionGroups as InteractionGroups,
    CollisionEventFlags as CollisionEventFlags,
    CollisionEvent as CollisionEvent,
    ContactForceEvent as ContactForceEvent,
    ContactData as ContactData,
    ContactManifold as ContactManifold,
    ContactManifoldData as ContactManifoldData,
    ContactPair as ContactPair,
    IntersectionPair as IntersectionPair,
    ColliderPair as ColliderPair,
    BroadPhasePairEvent as BroadPhasePairEvent,
    BroadPhaseBvh as BroadPhaseBvh,
    BvhOptimizationStrategy as BvhOptimizationStrategy,
    NarrowPhase as NarrowPhase,
    SolverContact as SolverContact,
    PhysicsPipeline as PhysicsPipeline,
    CollisionPipeline as CollisionPipeline,
    PhysicsWorld as PhysicsWorld,
    QueryPipeline as QueryPipeline,
    QueryFilter as QueryFilter,
    QueryFilterFlags as QueryFilterFlags,
    Ray as Ray,
    RayIntersection as RayIntersection,
    PointProjection as PointProjection,
    ShapeCastHit as ShapeCastHit,
    ShapeCastOptions as ShapeCastOptions,
    ShapeCastStatus as ShapeCastStatus,
    FeatureId as FeatureId,
    NonlinearRigidMotion as NonlinearRigidMotion,
    Counters as Counters,
    StagesCounters as StagesCounters,
    CollisionDetectionCounters as CollisionDetectionCounters,
    SolverCounters as SolverCounters,
    CCDCounters as CCDCounters,
    Quarantine as Quarantine,
    BuildFeatures as BuildFeatures,
    build_features as build_features,
    SolverFlags as SolverFlags,
    PairFilterContext as PairFilterContext,
    ContactModificationContext as ContactModificationContext,
    ChannelEventCollector as ChannelEventCollector,
    AxesMask as AxesMask,
    CharacterLength as CharacterLength,
    CharacterAutostep as CharacterAutostep,
    CharacterCollision as CharacterCollision,
    EffectiveCharacterMovement as EffectiveCharacterMovement,
    KinematicCharacterController as KinematicCharacterController,
    PdErrors as PdErrors,
    PidCorrection as PidCorrection,
    PdController as PdController,
    PidController as PidController,
    WheelTuning as WheelTuning,
    RayCastInfo as RayCastInfo,
    Wheel as Wheel,
    DynamicRayCastVehicleController as DynamicRayCastVehicleController,
    DebugRenderPipeline as DebugRenderPipeline,
    DebugRenderStyle as DebugRenderStyle,
    DebugRenderMode as DebugRenderMode,
    DebugRenderObject as DebugRenderObject,
    DebugColor as DebugColor,
    DebugLineCollector as DebugLineCollector,
)

__version__: str

__all__ = [
    "Vec3",
    "Point3",
    "Rotation3",
    "Quaternion",
    "Isometry3",
    "AngVector3",
    "rotation_from_angle",
    "RapierError",
    "InvalidHandle",
    "MeshConversionError",
    "UrdfError",
    "MjcfError",
    "SerializationError",
    "QueryFailure",
    "MeshLoaderError",
    "RigidBody",
    "RigidBodyBuilder",
    "RigidBodyHandle",
    "RigidBodySet",
    "RigidBodyType",
    "LockedAxes",
    "RigidBodyActivation",
    "RigidBodyDamping",
    "RigidBodyDominance",
    "RigidBodyCcd",
    "RigidBodyVelocity",
    "RigidBodyForces",
    "RigidBodyMassProps",
    "RigidBodyPosition",
    "RigidBodyAdditionalMassProps",
    "MassProperties",
    "IntegrationParameters",
    "SpringCoefficients",
    "CoefficientCombineRule",
    "FrictionModel",
    "IslandManager",
    "CCDSolver",
    "ImpulseJointSet",
    "MultibodyJointSet",
    "SoftBindingError",
    "SoftBodyHandle",
    "SoftBodyCellModel",
    "SoftEdgePlasticFlow",
    "SoftBodyEdgeKind",
    "SoftPatchConstraints",
    "SoftBodySolver",
    "SoftBodyMaterial",
    "SoftBodyParticleSettings",
    "SoftRecoverySettings",
    "SoftFemParameters",
    "SoftBodiesSettings",
    "MeshEnclosure",
    "VolumeMeshParameters",
    "SoftBodyBuilder",
    "SoftBodyParticle",
    "SoftBodyEdge",
    "SoftBodyDihedral",
    "SoftBodyCell",
    "SoftParticleAttachment",
    "SoftVolumePiece",
    "SoftBodyCluster",
    "SoftMeshId",
    "SoftMeshRef",
    "SoftCollisionMesh",
    "SoftMeshBinding",
    "SoftBodyPiece",
    "SoftClusterSplit",
    "SoftJointMove",
    "SoftBodyTearEvent",
    "SoftBody",
    "SoftBodySet",
    "JointEnabled",
    "MotorModel",
    "JointLimits",
    "JointMotor",
    "JointAxesMask",
    "JointAxis",
    "ImpulseJointHandle",
    "MultibodyJointHandle",
    "MultibodyIndex",
    "MultibodyLinkId",
    "InverseKinematicsOption",
    "FixedJoint",
    "FixedJointBuilder",
    "RevoluteJoint",
    "RevoluteJointBuilder",
    "PrismaticJoint",
    "PrismaticJointBuilder",
    "SphericalJoint",
    "SphericalJointBuilder",
    "RopeJoint",
    "RopeJointBuilder",
    "SpringJoint",
    "SpringJointBuilder",
    "GenericJoint",
    "GenericJointBuilder",
    "ImpulseJoint",
    "MultibodyLink",
    "Multibody",
    "MultibodyJoint",
    "Collider",
    "ColliderBuilder",
    "ColliderHandle",
    "ColliderSet",
    "ColliderType",
    "ColliderEnabled",
    "ColliderMaterial",
    "ColliderFlags",
    "ColliderParent",
    "ColliderPosition",
    "ColliderMassProps",
    "ShapeType",
    "SharedShape",
    "Ball",
    "Cuboid",
    "Capsule",
    "Triangle",
    "TriMesh",
    "HeightField",
    "Compound",
    "Voxels",
    "FillMode",
    "Cylinder",
    "Cone",
    "ConvexPolyhedron",
    "Aabb",
    "BoundingSphere",
    "MeshConverter",
    "TriMeshFlags",
    "ActiveEvents",
    "ActiveHooks",
    "ActiveCollisionTypes",
    "Group",
    "InteractionTestMode",
    "InteractionGroups",
    "CollisionEventFlags",
    "CollisionEvent",
    "ContactForceEvent",
    "ContactData",
    "ContactManifold",
    "ContactManifoldData",
    "ContactPair",
    "IntersectionPair",
    "ColliderPair",
    "BroadPhasePairEvent",
    "BroadPhaseBvh",
    "BvhOptimizationStrategy",
    "NarrowPhase",
    "SolverContact",
    "PhysicsPipeline",
    "CollisionPipeline",
    "PhysicsWorld",
    "QueryPipeline",
    "QueryFilter",
    "QueryFilterFlags",
    "Ray",
    "RayIntersection",
    "PointProjection",
    "ShapeCastHit",
    "ShapeCastOptions",
    "ShapeCastStatus",
    "FeatureId",
    "NonlinearRigidMotion",
    "Counters",
    "StagesCounters",
    "CollisionDetectionCounters",
    "SolverCounters",
    "CCDCounters",
    "Quarantine",
    "BuildFeatures",
    "build_features",
    "SolverFlags",
    "PairFilterContext",
    "ContactModificationContext",
    "ChannelEventCollector",
    "EventHandler",
    "PhysicsHooks",
    "AxesMask",
    "CharacterLength",
    "CharacterAutostep",
    "CharacterCollision",
    "EffectiveCharacterMovement",
    "KinematicCharacterController",
    "PdErrors",
    "PidCorrection",
    "PdController",
    "PidController",
    "WheelTuning",
    "RayCastInfo",
    "Wheel",
    "DynamicRayCastVehicleController",
    "DebugRenderPipeline",
    "DebugRenderStyle",
    "DebugRenderMode",
    "DebugRenderObject",
    "DebugColor",
    "DebugLineCollector",
    "DebugRenderBackend",
    "math",
    "__version__",
]
