"""Stub for `rapier3d.math`."""

from typing import TypeVar

from ._rapier3d import Rotation3 as _Rotation3
from ._rapier3d import VectorLike as _VectorLike

T = TypeVar("T")

def lerp(a: T, b: T, t: float) -> T: ...
def linear_interp(a: T, b: T, t: float) -> T: ...
def wrap_to_pi(angle: float) -> float: ...
def rotation_from_angle(v: _VectorLike) -> _Rotation3: ...

# Transcendental functions computed by Rapier's math backend (in f32), bit-identical on every
# platform when the bindings are built with the `determinism` feature.
def sin(x: float) -> float: ...
def cos(x: float) -> float: ...
def tan(x: float) -> float: ...
def asin(x: float) -> float: ...
def acos(x: float) -> float: ...
def atan(x: float) -> float: ...
def atan2(y: float, x: float) -> float: ...
def exp(x: float) -> float: ...
def log(x: float) -> float: ...
def pow(base: float, exponent: float) -> float: ...
def sqrt(x: float) -> float: ...
