"""Stub for `rapier.math`."""

from typing import TypeVar

from ._rapier3d import Rotation3 as _Rotation3

T = TypeVar("T")

def lerp(a: T, b: T, t: float) -> T: ...
def linear_interp(a: T, b: T, t: float) -> T: ...
def wrap_to_pi(angle: float) -> float: ...
def rotation_from_angle(v) -> _Rotation3: ...
