[package]
name = "ci"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_rapier3d = { version = "0.36", path = "../bevy_rapier3d" }
bevy_rapier2d = { version = "0.36", path = "../bevy_rapier2d" }

[[bin]]
name = "ambiguity_detection"
test = false
bench = false
