"""Type stubs for `rapier._rapier3d` (3D, f32).

Phase 02: math layer only.
"""

from __future__ import annotations

from typing import Any, Iterator, Tuple, Union

import numpy as np

__version__: str

# ---- Exception tree -------------------------------------------------------
class RapierError(Exception): ...
class InvalidHandle(RapierError): ...
class MeshConversionError(RapierError): ...
class UrdfError(RapierError): ...
class MjcfError(RapierError): ...
class SerializationError(RapierError): ...
class QueryFailure(RapierError): ...
class MeshLoaderError(RapierError): ...

# Anything that can be coerced to a 3-vector.
VectorLike = Union[
    "Vec3",
    "Point3",
    Tuple[float, float, float],
    list,
    "np.ndarray",
]
# Anything that can be coerced to a 4-tuple (x, y, z, w) → unit quaternion.
RotationLike = Union[
    "Rotation3",
    Tuple[float, float, float, float],
    list,
    "np.ndarray",
]
IsometryLike = Union["Isometry3", Tuple[VectorLike, RotationLike]]

# ---- Vec3 ----------------------------------------------------------------
class Vec3:
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @staticmethod
    def zeros() -> Vec3: ...
    @staticmethod
    def unit_x() -> Vec3: ...
    @staticmethod
    def unit_y() -> Vec3: ...
    @staticmethod
    def unit_z() -> Vec3: ...
    @staticmethod
    def from_tuple(t: VectorLike) -> Vec3: ...
    @staticmethod
    def from_ndarray(a: np.ndarray) -> Vec3: ...

    x: float
    y: float
    z: float

    def dot(self, other: VectorLike) -> float: ...
    def cross(self, other: VectorLike) -> Vec3: ...
    def norm(self) -> float: ...
    def norm_squared(self) -> float: ...
    def normalize(self) -> Vec3: ...
    def lerp(self, other: VectorLike, t: float) -> Vec3: ...
    def to_tuple(self) -> Tuple[float, float, float]: ...
    def to_ndarray(self) -> np.ndarray: ...
    def bitwise_equal(self, other: Vec3) -> bool: ...

    def __add__(self, other: VectorLike) -> Vec3: ...
    def __sub__(self, other: VectorLike) -> Vec3: ...
    def __mul__(self, scalar: float) -> Vec3: ...
    def __rmul__(self, scalar: float) -> Vec3: ...
    def __truediv__(self, scalar: float) -> Vec3: ...
    def __neg__(self) -> Vec3: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> float: ...
    def __iter__(self) -> Iterator[float]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

# `AngVector3` is a Python-level alias for `Vec3`.
AngVector3 = Vec3

# ---- Point3 --------------------------------------------------------------
class Point3:
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @staticmethod
    def origin() -> Point3: ...
    @staticmethod
    def from_tuple(t: VectorLike) -> Point3: ...
    @staticmethod
    def from_ndarray(a: np.ndarray) -> Point3: ...

    x: float
    y: float
    z: float
    coords: Vec3

    def to_tuple(self) -> Tuple[float, float, float]: ...
    def to_ndarray(self) -> np.ndarray: ...
    def lerp(self, other: VectorLike, t: float) -> Point3: ...
    def bitwise_equal(self, other: Point3) -> bool: ...

    def __add__(self, v: VectorLike) -> Point3: ...
    def __sub__(self, other: Any) -> Union[Point3, Vec3]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> float: ...
    def __iter__(self) -> Iterator[float]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

# ---- Rotation3 / Quaternion ---------------------------------------------
class Rotation3:
    def __init__(self, w: float = 1.0, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...
    @staticmethod
    def identity() -> Rotation3: ...
    @staticmethod
    def from_axis_angle(axis: VectorLike, angle: float) -> Rotation3: ...
    @staticmethod
    def from_euler_angles(roll: float, pitch: float, yaw: float) -> Rotation3: ...
    @staticmethod
    def from_scaled_axis(v: VectorLike) -> Rotation3: ...
    @staticmethod
    def from_quaternion(w: float, x: float, y: float, z: float) -> Rotation3: ...
    @staticmethod
    def look_at_lh(dir: VectorLike, up: VectorLike) -> Rotation3: ...
    @staticmethod
    def look_at_rh(dir: VectorLike, up: VectorLike) -> Rotation3: ...
    @staticmethod
    def face_toward(dir: VectorLike, up: VectorLike) -> Rotation3: ...
    @staticmethod
    def from_tuple(t: RotationLike) -> Rotation3: ...
    @staticmethod
    def from_ndarray(a: np.ndarray) -> Rotation3: ...

    axis: Vec3 | None
    angle: float
    scaled_axis: Vec3
    euler_angles: Tuple[float, float, float]
    quaternion: Tuple[float, float, float, float]
    w: float
    i: float
    j: float
    k: float

    def inverse(self) -> Rotation3: ...
    def to_matrix(self) -> np.ndarray: ...
    def transform_point(self, p: VectorLike) -> Point3: ...
    def transform_vector(self, v: VectorLike) -> Vec3: ...
    def slerp(self, other: RotationLike, t: float) -> Rotation3: ...
    def bitwise_equal(self, other: Rotation3) -> bool: ...

    def __mul__(self, rhs: Any) -> Any: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

# Alias: `Quaternion is Rotation3`.
Quaternion = Rotation3

# ---- Isometry3 -----------------------------------------------------------
class Isometry3:
    def __init__(
        self,
        translation: VectorLike | None = None,
        rotation: RotationLike | None = None,
    ) -> None: ...
    @staticmethod
    def identity() -> Isometry3: ...
    @staticmethod
    def from_translation(x: float, y: float, z: float) -> Isometry3: ...
    @staticmethod
    def from_rotation(scaled_axis: VectorLike) -> Isometry3: ...
    @staticmethod
    def face_toward(eye: VectorLike, target: VectorLike, up: VectorLike) -> Isometry3: ...
    @staticmethod
    def look_at_lh(eye: VectorLike, target: VectorLike, up: VectorLike) -> Isometry3: ...
    @staticmethod
    def look_at_rh(eye: VectorLike, target: VectorLike, up: VectorLike) -> Isometry3: ...

    @property
    def translation(self) -> Vec3: ...
    @property
    def rotation(self) -> Rotation3: ...

    def inverse(self) -> Isometry3: ...
    def transform_point(self, p: VectorLike) -> Point3: ...
    def transform_vector(self, v: VectorLike) -> Vec3: ...
    def to_matrix(self) -> np.ndarray: ...
    def lerp_slerp(self, other: Isometry3, t: float) -> Isometry3: ...
    def bitwise_equal(self, other: Isometry3) -> bool: ...

    def __mul__(self, rhs: Any) -> Any: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

# ---- Free helpers --------------------------------------------------------
def rotation_from_angle(v: VectorLike) -> Rotation3: ...

# =====================================================================
# Phase 03 — Dynamics
# =====================================================================

import enum

class RigidBodyType(enum.IntEnum):
    DYNAMIC: int
    FIXED: int
    KINEMATIC_VELOCITY_BASED: int
    KINEMATIC_POSITION_BASED: int

class CoefficientCombineRule(enum.IntEnum):
    AVERAGE: int
    MIN: int
    MULTIPLY: int
    MAX: int
    CLAMPED_SUM: int

class FrictionModel(enum.IntEnum):
    COEFFICIENT: int
    COULOMB: int

class ColliderHandle:
    def __init__(self, index: int = 0, generation: int = 0) -> None: ...
    @staticmethod
    def from_raw_parts(index: int, generation: int) -> ColliderHandle: ...
    @staticmethod
    def invalid() -> ColliderHandle: ...
    @property
    def index(self) -> int: ...
    @property
    def generation(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class ColliderSet:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...

class ImpulseJointSet:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...

class MultibodyJointSet:
    def __init__(self) -> None: ...

class RigidBodyHandle:
    def __init__(self, index: int = 0, generation: int = 0) -> None: ...
    @staticmethod
    def from_raw_parts(index: int, generation: int) -> RigidBodyHandle: ...
    @staticmethod
    def invalid() -> RigidBodyHandle: ...
    @property
    def index(self) -> int: ...
    @property
    def generation(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class LockedAxes:
    TRANSLATION_LOCKED_X: LockedAxes
    TRANSLATION_LOCKED_Y: LockedAxes
    TRANSLATION_LOCKED_Z: LockedAxes
    TRANSLATION_LOCKED: LockedAxes
    ROTATION_LOCKED_X: LockedAxes
    ROTATION_LOCKED_Y: LockedAxes
    ROTATION_LOCKED_Z: LockedAxes
    ROTATION_LOCKED: LockedAxes
    ALL: LockedAxes
    def __init__(self, bits: int = 0) -> None: ...
    @staticmethod
    def empty() -> LockedAxes: ...
    @staticmethod
    def all_axes() -> LockedAxes: ...
    @property
    def bits(self) -> int: ...
    def contains(self, other: LockedAxes) -> bool: ...
    def is_empty(self) -> bool: ...
    def __or__(self, other: LockedAxes) -> LockedAxes: ...
    def __and__(self, other: LockedAxes) -> LockedAxes: ...
    def __xor__(self, other: LockedAxes) -> LockedAxes: ...
    def __invert__(self) -> LockedAxes: ...

class RigidBodyActivation:
    sleep_threshold: float
    linear_threshold: float
    angular_threshold: float
    time_until_sleep: float
    sleeping: bool
    def __init__(self) -> None: ...
    @staticmethod
    def active() -> RigidBodyActivation: ...
    @staticmethod
    def inactive() -> RigidBodyActivation: ...
    @staticmethod
    def cannot_sleep() -> RigidBodyActivation: ...
    def is_active(self) -> bool: ...

class SpringCoefficients:
    stiffness: float
    damping: float
    natural_frequency: float
    damping_ratio: float
    def __init__(self, stiffness: float = 30.0, damping: float = 5.0) -> None: ...
    @staticmethod
    def contact_defaults() -> SpringCoefficients: ...
    @staticmethod
    def joint_defaults() -> SpringCoefficients: ...

class MassProperties:
    def __init__(
        self,
        local_com: VectorLike | None = None,
        mass: float = 0.0,
        principal_inertia: VectorLike | None = None,
        principal_inertia_local_frame: RotationLike | None = None,
    ) -> None: ...
    @staticmethod
    def zero() -> MassProperties: ...
    @staticmethod
    def from_ball(density: float, radius: float) -> MassProperties: ...
    @staticmethod
    def from_cuboid(density: float, half_extents: VectorLike) -> MassProperties: ...
    @staticmethod
    def from_capsule(density: float, a: VectorLike, b: VectorLike, radius: float) -> MassProperties: ...
    @staticmethod
    def from_cylinder(density: float, half_height: float, radius: float) -> MassProperties: ...
    @staticmethod
    def from_cone(density: float, half_height: float, radius: float) -> MassProperties: ...
    @property
    def mass(self) -> float: ...
    @property
    def inv_mass(self) -> float: ...
    @property
    def local_com(self) -> Point3: ...
    @property
    def principal_inertia(self) -> Vec3: ...
    @property
    def principal_inertia_local_frame(self) -> Rotation3: ...
    def transform_by(self, iso: IsometryLike) -> MassProperties: ...
    def __add__(self, other: MassProperties) -> MassProperties: ...
    def __sub__(self, other: MassProperties) -> MassProperties: ...

class RigidBodyAdditionalMassProps:
    @staticmethod
    def from_mass(mass: float) -> RigidBodyAdditionalMassProps: ...
    @staticmethod
    def from_mass_properties(mp: MassProperties) -> RigidBodyAdditionalMassProps: ...

class RigidBodyDamping:
    linear_damping: float
    angular_damping: float
    def __init__(self, linear_damping: float = 0.0, angular_damping: float = 0.0) -> None: ...

class RigidBodyDominance:
    group: int
    def __init__(self, group: int = 0) -> None: ...

class RigidBodyCcd:
    ccd_enabled: bool
    soft_ccd_prediction: float
    def __init__(self, ccd_enabled: bool = False, soft_ccd_prediction: float = 0.0) -> None: ...

class RigidBodyVelocity:
    linvel: Vec3
    angvel: Vec3
    def __init__(self, linvel: VectorLike | None = None, angvel: VectorLike | None = None) -> None: ...

class RigidBodyForces:
    force: Vec3
    torque: Vec3
    gravity_scale: float

class RigidBodyMassProps:
    local_mprops: MassProperties

class RigidBodyPosition:
    position: Isometry3
    next_position: Isometry3

class IntegrationParameters:
    dt: float
    min_ccd_dt: float
    warmstart_coefficient: float
    length_unit: float
    normalized_allowed_linear_error: float
    normalized_max_corrective_velocity: float
    normalized_prediction_distance: float
    num_solver_iterations: int
    num_internal_pgs_iterations: int
    num_internal_stabilization_iterations: int
    min_island_size: int
    max_ccd_substeps: int
    contact_softness: SpringCoefficients
    friction_model: FrictionModel
    def __init__(self) -> None: ...
    @staticmethod
    def default_params() -> IntegrationParameters: ...
    def inv_dt(self) -> float: ...
    def allowed_linear_error(self) -> float: ...
    def max_corrective_velocity(self) -> float: ...
    def prediction_distance(self) -> float: ...
    def contact_spring_stiffness(self) -> float: ...
    def contact_spring_damping(self) -> float: ...
    def joint_spring_stiffness(self) -> float: ...
    def joint_spring_damping(self) -> float: ...

class IslandManager:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[RigidBodyHandle]: ...
    def active_dynamic_set(self) -> list[RigidBodyHandle]: ...
    def contains_handle(self, h: RigidBodyHandle) -> bool: ...
    def same_island(self, h1: RigidBodyHandle, h2: RigidBodyHandle) -> bool: ...
    def active_set_offset(self, h: RigidBodyHandle) -> int: ...

class CCDSolver:
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def solve_ccd(self, *args: Any, **kwargs: Any) -> None: ...

class RigidBodyBuilder:
    def __init__(self, body_type: RigidBodyType = ...) -> None: ...
    def translation(self, v: VectorLike) -> RigidBodyBuilder: ...
    def rotation(self, scaled_axis: VectorLike) -> RigidBodyBuilder: ...
    def position(self, p: IsometryLike) -> RigidBodyBuilder: ...
    def linvel(self, v: VectorLike) -> RigidBodyBuilder: ...
    def angvel(self, v: VectorLike) -> RigidBodyBuilder: ...
    def linear_damping(self, f: float) -> RigidBodyBuilder: ...
    def angular_damping(self, f: float) -> RigidBodyBuilder: ...
    def gravity_scale(self, f: float) -> RigidBodyBuilder: ...
    def can_sleep(self, b: bool) -> RigidBodyBuilder: ...
    def sleeping(self, b: bool) -> RigidBodyBuilder: ...
    def ccd_enabled(self, b: bool) -> RigidBodyBuilder: ...
    def soft_ccd_prediction(self, f: float) -> RigidBodyBuilder: ...
    def dominance_group(self, g: int) -> RigidBodyBuilder: ...
    def additional_solver_iterations(self, n: int) -> RigidBodyBuilder: ...
    def user_data(self, d: int) -> RigidBodyBuilder: ...
    def enabled(self, b: bool) -> RigidBodyBuilder: ...
    def additional_mass(self, m: float) -> RigidBodyBuilder: ...
    def additional_mass_properties(self, mp: MassProperties) -> RigidBodyBuilder: ...
    def locked_axes(self, la: LockedAxes) -> RigidBodyBuilder: ...
    def enabled_translations(self, t: tuple[bool, bool, bool]) -> RigidBodyBuilder: ...
    def restrict_translations(self, t: tuple[bool, bool, bool]) -> RigidBodyBuilder: ...
    def enabled_rotations(self, t: tuple[bool, bool, bool]) -> RigidBodyBuilder: ...
    def restrict_rotations(self, t: tuple[bool, bool, bool]) -> RigidBodyBuilder: ...
    def gyroscopic_forces(self, b: bool) -> RigidBodyBuilder: ...
    def build(self) -> RigidBody: ...

class RigidBody:
    position: Isometry3
    translation: Vec3
    rotation: Rotation3
    linvel: Vec3
    angvel: Vec3
    user_data: int
    body_type: RigidBodyType
    gravity_scale: float
    linear_damping: float
    angular_damping: float
    dominance_group: int
    additional_solver_iterations: int
    locked_axes: LockedAxes
    enabled_translations: tuple[bool, bool, bool]
    enabled_rotations: tuple[bool, bool, bool]
    is_enabled: bool
    ccd_enabled: bool
    soft_ccd_prediction: float
    gyroscopic_forces_enabled: bool
    activation: RigidBodyActivation
    @property
    def mass(self) -> float: ...
    @property
    def inv_mass(self) -> float: ...
    @property
    def center_of_mass(self) -> Point3: ...
    @property
    def local_center_of_mass(self) -> Point3: ...
    @property
    def mass_properties(self) -> MassProperties: ...
    @property
    def is_sleeping(self) -> bool: ...
    @property
    def is_moving(self) -> bool: ...
    @property
    def is_dynamic(self) -> bool: ...
    @property
    def is_kinematic(self) -> bool: ...
    @property
    def is_fixed(self) -> bool: ...
    @property
    def user_force(self) -> Vec3: ...
    @property
    def user_torque(self) -> Vec3: ...
    @property
    def colliders(self) -> list[ColliderHandle]: ...
    @property
    def next_position(self) -> Isometry3: ...
    @staticmethod
    def dynamic(**kwargs: Any) -> RigidBodyBuilder: ...
    @staticmethod
    def fixed(**kwargs: Any) -> RigidBodyBuilder: ...
    @staticmethod
    def kinematic_velocity_based(**kwargs: Any) -> RigidBodyBuilder: ...
    @staticmethod
    def kinematic_position_based(**kwargs: Any) -> RigidBodyBuilder: ...
    @staticmethod
    def new_body(body_type: RigidBodyType, **kwargs: Any) -> RigidBodyBuilder: ...
    def add_force(self, force: VectorLike, wake_up: bool = True) -> None: ...
    def add_torque(self, torque: VectorLike, wake_up: bool = True) -> None: ...
    def add_force_at_point(self, force: VectorLike, point: VectorLike, wake_up: bool = True) -> None: ...
    def apply_impulse(self, impulse: VectorLike, wake_up: bool = True) -> None: ...
    def apply_torque_impulse(self, torque_impulse: VectorLike, wake_up: bool = True) -> None: ...
    def apply_impulse_at_point(self, impulse: VectorLike, point: VectorLike, wake_up: bool = True) -> None: ...
    def add_gravitational_force(self, gravity: VectorLike) -> None: ...
    def reset_forces(self, wake_up: bool = True) -> None: ...
    def reset_torques(self, wake_up: bool = True) -> None: ...
    def wake_up(self, strong: bool = True) -> None: ...
    def sleep(self) -> None: ...
    def velocity_at_point(self, point: VectorLike) -> Vec3: ...
    def kinetic_energy(self) -> float: ...
    def gravitational_potential_energy(self, dt: float, gravity: VectorLike) -> float: ...
    def predict_position_using_velocity(self, dt: float) -> Isometry3: ...
    def predict_position_using_velocity_and_forces(self, dt: float) -> Isometry3: ...
    def angvel_with_gyroscopic_forces(self, dt: float) -> Vec3: ...
    def recompute_mass_properties_from_colliders(self, colliders: ColliderSet) -> None: ...
    def set_additional_mass(self, mass: float, wake_up: bool = True) -> None: ...
    def set_additional_mass_properties(self, mp: MassProperties, wake_up: bool = True) -> None: ...

class RigidBodySet:
    def __init__(self) -> None: ...
    def insert(self, body: RigidBody | RigidBodyBuilder) -> RigidBodyHandle: ...
    def remove(
        self,
        handle: RigidBodyHandle,
        islands: IslandManager,
        colliders: ColliderSet,
        impulse_joints: ImpulseJointSet,
        multibody_joints: MultibodyJointSet,
        remove_attached_colliders: bool = True,
    ) -> RigidBody | None: ...
    def get(self, handle: RigidBodyHandle) -> RigidBody | None: ...
    def clear(self) -> None: ...
    def handles(self) -> Iterator[RigidBodyHandle]: ...
    def __getitem__(self, handle: RigidBodyHandle) -> RigidBody: ...
    def __contains__(self, handle: RigidBodyHandle) -> bool: ...
    def __iter__(self) -> Iterator[Tuple[RigidBodyHandle, RigidBody]]: ...
    def __len__(self) -> int: ...

# ---- events / hooks (phase 07) -------------------------------------------

class SolverFlags:
    COMPUTE_IMPULSES: SolverFlags
    EMPTY: SolverFlags
    def __init__(self, bits: int = 0) -> None: ...
    @staticmethod
    def empty() -> SolverFlags: ...
    @property
    def bits(self) -> int: ...
    def contains(self, other: SolverFlags) -> bool: ...
    def is_empty(self) -> bool: ...
    def __or__(self, other: SolverFlags) -> SolverFlags: ...
    def __and__(self, other: SolverFlags) -> SolverFlags: ...
    def __xor__(self, other: SolverFlags) -> SolverFlags: ...
    def __invert__(self) -> SolverFlags: ...

class PairFilterContext:
    @property
    def collider1(self) -> ColliderHandle: ...
    @property
    def collider2(self) -> ColliderHandle: ...
    @property
    def rigid_body1(self) -> RigidBodyHandle | None: ...
    @property
    def rigid_body2(self) -> RigidBodyHandle | None: ...

class ContactModificationContext:
    @property
    def collider1(self) -> ColliderHandle: ...
    @property
    def collider2(self) -> ColliderHandle: ...
    @property
    def rigid_body1(self) -> RigidBodyHandle | None: ...
    @property
    def rigid_body2(self) -> RigidBodyHandle | None: ...
    @property
    def local_n1(self) -> Vec3: ...
    @property
    def local_n2(self) -> Vec3: ...
    normal: Vec3
    user_data: int
    @property
    def solver_contacts(self) -> list[SolverContact]: ...
    def clear_solver_contacts(self) -> None: ...
    def num_solver_contacts(self) -> int: ...
    def remove_solver_contact(self, i: int) -> None: ...
    def update_as_oneway_platform(self, allowed_local_n1: Vec3 | tuple[float, float, float], angle: float) -> None: ...

class ChannelEventCollector:
    def __init__(self) -> None: ...
    def drain_collision_events(self) -> list[CollisionEvent]: ...
    def drain_contact_force_events(self) -> list[ContactForceEvent]: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def remove_solver_contact(self, i: int) -> None: ...
    def update_as_oneway_platform(self, allowed_local_n1: Vec3 | tuple[float, float, float], angle: float) -> None: ...

class ChannelEventCollector:
    def __init__(self) -> None: ...
    def drain_collision_events(self) -> list[CollisionEvent]: ...
    def drain_contact_force_events(self) -> list[ContactForceEvent]: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...

# ---- controllers (phase 08) ----------------------------------------------

from typing import Callable, Literal

class CharacterLength:
    kind: Literal["absolute", "relative"]
    value: float
    def __init__(self, value: float = 0.0, kind: str = "absolute") -> None: ...
    @staticmethod
    def absolute(value: float) -> CharacterLength: ...
    @staticmethod
    def relative(value: float) -> CharacterLength: ...

class CharacterAutostep:
    max_height: CharacterLength
    min_width: CharacterLength
    include_dynamic_bodies: bool
    def __init__(
        self,
        max_height: CharacterLength | float | None = None,
        min_width: CharacterLength | float | None = None,
        include_dynamic_bodies: bool = True,
    ) -> None: ...
    @staticmethod
    def disabled() -> None: ...

class EffectiveCharacterMovement:
    @property
    def translation(self) -> Vec3: ...
    @property
    def grounded(self) -> bool: ...
    @property
    def is_sliding_down_slope(self) -> bool: ...

class CharacterCollision:
    @property
    def handle(self) -> ColliderHandle: ...
    @property
    def character_pos(self) -> Isometry3: ...
    @property
    def translation_applied(self) -> Vec3: ...
    @property
    def translation_remaining(self) -> Vec3: ...
    @property
    def toi(self) -> ShapeCastHit: ...

class KinematicCharacterController:
    up: Vec3
    offset: CharacterLength
    slide: bool
    autostep: CharacterAutostep | None
    max_slope_climb_angle: float
    min_slope_slide_angle: float
    snap_to_ground: CharacterLength | None
    normal_nudge_factor: float
    def __init__(
        self,
        *,
        up: Vec3 | tuple[float, float, float] | None = None,
        offset: CharacterLength | float | None = None,
        slide: bool | None = None,
        autostep: CharacterAutostep | None = None,
        max_slope_climb_angle: float | None = None,
        min_slope_slide_angle: float | None = None,
        snap_to_ground: CharacterLength | float | None = None,
        normal_nudge_factor: float | None = None,
    ) -> None: ...
    def move_shape(
        self,
        dt: float,
        bodies: RigidBodySet,
        colliders: ColliderSet,
        queries: QueryPipeline,
        shape: SharedShape,
        shape_pos: Isometry3,
        desired_translation: Vec3 | tuple[float, float, float],
        filter: QueryFilter | None = None,
        events_callback: Callable[[CharacterCollision], None] | None = None,
    ) -> EffectiveCharacterMovement: ...
    def solve_character_collision_impulses(
        self,
        dt: float,
        bodies: RigidBodySet,
        colliders: ColliderSet,
        queries: QueryPipeline,
        character_shape: SharedShape,
        character_pos: Isometry3,
        character_mass: float,
        collisions: list[CharacterCollision],
        filter: QueryFilter | None = None,
    ) -> None: ...

class AxesMask:
    LIN_X: AxesMask
    LIN_Y: AxesMask
    LIN_Z: AxesMask
    ANG_X: AxesMask
    ANG_Y: AxesMask
    ANG_Z: AxesMask
    def __init__(self, bits: int = 0) -> None: ...
    @staticmethod
    def empty() -> AxesMask: ...
    @staticmethod
    def all() -> AxesMask: ...
    @staticmethod
    def all_axes() -> AxesMask: ...
    @property
    def bits(self) -> int: ...
    def contains(self, other: AxesMask) -> bool: ...
    def is_empty(self) -> bool: ...
    def __or__(self, other: AxesMask) -> AxesMask: ...
    def __and__(self, other: AxesMask) -> AxesMask: ...
    def __xor__(self, other: AxesMask) -> AxesMask: ...
    def __invert__(self) -> AxesMask: ...
    def __sub__(self, other: AxesMask) -> AxesMask: ...
    def __contains__(self, other: AxesMask) -> bool: ...

class PdErrors:
    linear: Vec3
    angular: Vec3
    def __init__(
        self,
        linear: Vec3 | tuple[float, float, float] | None = None,
        angular: Vec3 | tuple[float, float, float] | None = None,
    ) -> None: ...

class PidCorrection:
    @property
    def linear(self) -> Vec3: ...
    @property
    def angular(self) -> Vec3: ...

class PdController:
    axes: AxesMask
    def __init__(
        self,
        axes: AxesMask | None = None,
        Kp: Vec3 | tuple[float, float, float] | float | None = None,
        Kd: Vec3 | tuple[float, float, float] | float | None = None,
    ) -> None: ...
    def set_axes_kp(self, v: Vec3 | tuple[float, float, float]) -> None: ...
    def set_axes_kd(self, v: Vec3 | tuple[float, float, float]) -> None: ...
    def rigid_body_correction(self, body: RigidBody, target_pose: Isometry3) -> PidCorrection: ...
    def correction(self, pose_errors: PdErrors, vel_errors: PdErrors) -> PidCorrection: ...

class PidController:
    axes: AxesMask
    def __init__(
        self,
        axes: AxesMask | None = None,
        Kp: Vec3 | tuple[float, float, float] | float | None = None,
        Ki: Vec3 | tuple[float, float, float] | float | None = None,
        Kd: Vec3 | tuple[float, float, float] | float | None = None,
    ) -> None: ...
    def set_axes_kp(self, v: Vec3 | tuple[float, float, float]) -> None: ...
    def set_axes_ki(self, v: Vec3 | tuple[float, float, float]) -> None: ...
    def set_axes_kd(self, v: Vec3 | tuple[float, float, float]) -> None: ...
    def reset(self) -> None: ...
    def rigid_body_correction(self, dt: float, body: RigidBody, target_pose: Isometry3) -> PidCorrection: ...
    def position_correction(self, dt: float, position: Isometry3, target_position: Isometry3) -> PidCorrection: ...
    def update(self, dt: float, pose_errors: PdErrors, vel_errors: PdErrors) -> PidCorrection: ...

class WheelTuning:
    suspension_stiffness: float
    suspension_compression: float
    suspension_damping: float
    max_suspension_travel: float
    side_friction_stiffness: float
    friction_slip: float
    max_suspension_force: float
    def __init__(
        self,
        suspension_stiffness: float | None = None,
        suspension_compression: float | None = None,
        suspension_damping: float | None = None,
        max_suspension_travel: float | None = None,
        side_friction_stiffness: float | None = None,
        friction_slip: float | None = None,
        max_suspension_force: float | None = None,
    ) -> None: ...
    @staticmethod
    def default() -> WheelTuning: ...

class RayCastInfo:
    @property
    def contact_normal_ws(self) -> Vec3: ...
    @property
    def contact_point_ws(self) -> Vec3: ...
    @property
    def suspension_length(self) -> float: ...
    @property
    def hard_point_ws(self) -> Vec3: ...
    @property
    def is_in_contact(self) -> bool: ...
    @property
    def ground_object(self) -> ColliderHandle | None: ...

class Wheel:
    chassis_connection_point_cs: Vec3
    direction_cs: Vec3
    axle_cs: Vec3
    suspension_rest_length: float
    max_suspension_travel: float
    radius: float
    suspension_stiffness: float
    damping_compression: float
    damping_relaxation: float
    friction_slip: float
    side_friction_stiffness: float
    rotation: float
    max_suspension_force: float
    forward_impulse: float
    side_impulse: float
    steering: float
    engine_force: float
    brake: float
    wheel_suspension_force: float
    @property
    def raycast_info(self) -> RayCastInfo: ...

class DynamicRayCastVehicleController:
    index_up_axis: int
    index_forward_axis: int
    def __init__(self, chassis_handle: RigidBodyHandle) -> None: ...
    def add_wheel(
        self,
        chassis_connection_cs: Vec3 | tuple[float, float, float],
        direction_cs: Vec3 | tuple[float, float, float],
        axle_cs: Vec3 | tuple[float, float, float],
        suspension_rest_length: float,
        radius: float,
        tuning: WheelTuning,
    ) -> int: ...
    def update_vehicle(
        self,
        dt: float,
        bodies: RigidBodySet,
        colliders: ColliderSet,
        queries: QueryPipeline,
        filter: QueryFilter | None = None,
    ) -> None: ...
    def set_brake(self, idx: int, brake: float) -> None: ...
    def set_steering(self, idx: int, steering: float) -> None: ...
    def apply_engine_force(self, idx: int, force: float) -> None: ...
    def wheels(self) -> list[Wheel]: ...
    def wheel(self, idx: int) -> Wheel: ...
    def current_speed_km_hour(self) -> float: ...
    @property
    def current_vehicle_speed(self) -> float: ...
    def chassis(self) -> RigidBodyHandle: ...

# ---- debug-render (phase 10) ---------------------------------------------

class DebugRenderObject:
    kind: int
    RIGID_BODY: DebugRenderObject
    COLLIDER: DebugRenderObject
    COLLIDER_AABB: DebugRenderObject
    IMPULSE_JOINT: DebugRenderObject
    MULTIBODY_JOINT: DebugRenderObject
    CONTACT_PAIR: DebugRenderObject

class DebugColor:
    def __init__(self, h: float = 0.0, s: float = 0.0, l: float = 0.0, a: float = 1.0) -> None: ...
    @staticmethod
    def from_hsla(h: float, s: float, l: float, a: float) -> DebugColor: ...
    @staticmethod
    def from_rgba(r: float, g: float, b: float, a: float) -> DebugColor: ...
    @property
    def hsla(self) -> list[float]: ...
    @property
    def rgba(self) -> list[float]: ...

class DebugRenderMode:
    def __init__(self, bits: int = 0) -> None: ...
    @staticmethod
    def empty() -> DebugRenderMode: ...
    @staticmethod
    def default() -> DebugRenderMode: ...
    @staticmethod
    def all() -> DebugRenderMode: ...
    COLLIDER_SHAPES: DebugRenderMode
    RIGID_BODY_AXES: DebugRenderMode
    MULTIBODY_JOINTS: DebugRenderMode
    IMPULSE_JOINTS: DebugRenderMode
    JOINTS: DebugRenderMode
    SOLVER_CONTACTS: DebugRenderMode
    CONTACTS: DebugRenderMode
    COLLIDER_AABBS: DebugRenderMode
    EMPTY: DebugRenderMode
    @property
    def bits(self) -> int: ...
    def contains(self, other: DebugRenderMode) -> bool: ...
    def is_empty(self) -> bool: ...
    def __or__(self, other: DebugRenderMode) -> DebugRenderMode: ...
    def __and__(self, other: DebugRenderMode) -> DebugRenderMode: ...
    def __xor__(self, other: DebugRenderMode) -> DebugRenderMode: ...
    def __invert__(self) -> DebugRenderMode: ...
    def __bool__(self) -> bool: ...

class DebugRenderStyle:
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> DebugRenderStyle: ...
    subdivisions: int
    border_subdivisions: int
    collider_dynamic_color: DebugColor
    collider_fixed_color: DebugColor
    collider_kinematic_color: DebugColor
    collider_parentless_color: DebugColor
    impulse_joint_anchor_color: DebugColor
    impulse_joint_separation_color: DebugColor
    multibody_joint_anchor_color: DebugColor
    multibody_joint_separation_color: DebugColor
    sleep_color_multiplier: DebugColor
    disabled_color_multiplier: DebugColor
    rigid_body_axes_length: float
    contact_depth_color: DebugColor
    contact_normal_color: DebugColor
    contact_normal_length: float
    collider_aabb_color: DebugColor

class DebugLineCollector:
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def lines(self) -> np.ndarray: ...
    def colors(self) -> np.ndarray: ...
    def objects(self) -> np.ndarray: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[tuple[DebugRenderObject, Vec3, Vec3, DebugColor]]: ...

class DebugRenderPipeline:
    mode: DebugRenderMode
    style: DebugRenderStyle
    def __init__(
        self,
        mode: DebugRenderMode | None = None,
        style: DebugRenderStyle | None = None,
    ) -> None: ...
    def render(
        self,
        bodies: RigidBodySet,
        colliders: ColliderSet,
        impulse_joints: ImpulseJointSet,
        multibody_joints: MultibodyJointSet,
        narrow_phase: NarrowPhase,
        backend: Any,
    ) -> None: ...
    def render_to_arrays(
        self,
        bodies: RigidBodySet,
        colliders: ColliderSet,
        impulse_joints: ImpulseJointSet,
        multibody_joints: MultibodyJointSet,
        narrow_phase: NarrowPhase,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...
